// consultingCaseContent.js
// 6 reference-quality cases (the 5 from Pass 1, upgraded to the richer data model, plus 1 new
// Pricing case) — quality over volume, per the Pass-2 spec. Every quantProblem's correctAnswer is
// hand-verified against the case's own exhibits (see inline math notes). Grading metadata
// (interviewerNotes/gradingEvidence/idealInsights/commonMistakes/recommendationCriteria) is never
// shown to the candidate — consultingCaseEngine.js/consultingCasePanel.jsx must not render it.
//
// Case shape:
// {id,label,title,industry,caseType,difficulty,estimatedMin,supportedFirmStyles,description,
//  prompt,objective:{components,constraints,successCriteria},hiddenFacts:[{id,category,fact,
//  revealPolicy}],exhibits:[...exhibit schema, each +revealPolicy],quantProblems:[{id,prompt,
//  type:'numeric',correctAnswer,toleranceAbs|tolerancePct,unit,modelAnswer,relatedExhibitId?,
//  competency,requiresSoWhat}],brainstormPrompts:[{id,prompt,competency,modelCategories}],
//  synthesisMoments:[{id,triggerPhase,prompt,idealSynthesis}],
//  recommendationCriteria:{mustAddress,strongAnswerLooksLike,conclusion},interviewerNotes,
//  gradingEvidence:{opening,structure,exploration,synthesis,recommendation},idealInsights,
//  commonMistakes}

const CASES_CATALOG=[
{
  id:'profitability', label:'Profitability', caseType:'profitability', difficulty:'Intermediate', estimatedMin:25,
  supportedFirmStyles:['general','mckinsey','bcg','bain','oliverWyman'],
  title:'Specialty Retail Profitability', industry:'Retail',
  description:'A specialty retailer\'s margin fell from 8% to 3%. Revenue held flat at $800M. Find the root cause and a fix.',
  prompt:'Our client is a mid-size specialty retail chain with 200 stores across the US. Their net profit margin has declined from 8% to 3% over the past two years, despite revenue holding flat at approximately $800M. The CEO wants to understand why margins fell and what they should do about it.',
  objective:{ components:['diagnose the root causes of the margin decline','recommend actions to restore profitability'],
    constraints:['US market','200-store retail chain','revenue has held flat at $800M'],
    successCriteria:'restore net profit margin toward the historical 8% level' },
  hiddenFacts:[
    {id:'timeframe', category:'scope', fact:'The decline happened over the past 2 fiscal years; management wants a plan executable within 12-18 months.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'store-mix', category:'operations', fact:'All 200 stores are company-owned (no franchising) and carry a similar product assortment.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'competitor-context', category:'market', fact:'The two closest competitors have held margins roughly flat over the same period.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'labor-negotiations', category:'operations', fact:'A regional minimum-wage increase and a tight labor market drove most of the wage inflation.', revealPolicy:'NOT_AVAILABLE'},
  ],
  exhibits:[
    {id:'ex1', type:'pnl', title:'P&L Summary, Two Years', revealPolicy:'PROACTIVELY_GIVEN', unit:'% of revenue',
      data:{ unit:'%', rows:[
        {label:'Revenue', value:100, isTotal:false},
        {label:'COGS (2 yrs ago)', value:58}, {label:'COGS (today)', value:64},
        {label:'Labor (2 yrs ago)', value:20}, {label:'Labor (today)', value:22},
        {label:'Rent & D&A', value:14},
        {label:'Net margin (2 yrs ago)', value:8, isTotal:true}, {label:'Net margin (today)', value:3, isTotal:true},
      ]}, sourceNote:'Internal financial reporting.' },
    {id:'ex2', type:'stackedBar', title:'Revenue by Channel', revealPolicy:'AVAILABLE_ON_REQUEST', unit:'$M',
      data:{ categories:['2 yrs ago','Today'], valueUnit:'$M', series:[
        {label:'In-Store', values:[720,600]}, {label:'Online', values:[80,200]},
      ]}, footnote:'Online gross margin runs ~3 percentage points below in-store.', sourceNote:'Channel P&L reporting.' },
    {id:'ex3', type:'line', title:'Transaction Volume vs. Average Price', revealPolicy:'AVAILABLE_ON_REQUEST',
      data:{ xLabels:['2 yrs ago','Today'], series:[
        {label:'Transaction Volume (index)', values:[100,88]},
        {label:'Average Price (index)', values:[100,108]},
      ]}, footnote:'Indexed to 100 = 2 years ago. Independent scales.', sourceNote:'POS transaction data.' },
  ],
  quantProblems:[
    {id:'q1', prompt:'COGS rose from 58% to 64% of revenue (a 6-percentage-point increase) on $800M revenue. Approximately how much did this cost the company in annual profit?', type:'numeric',
      correctAnswer:48000000, tolerancePct:5, unit:'$', relatedExhibitId:'ex1', competency:'quantitativeReasoning', requiresSoWhat:true,
      modelAnswer:'6% of $800M = $48M in additional annual cost — the single largest driver of the margin decline by itself.'},
  ],
  synthesisMoments:[
    {id:'s1', triggerPhase:'exploration', prompt:'After reviewing the P&L and channel exhibits, what is your interim synthesis?',
      idealSynthesis:'The decline is driven mostly by COGS margin compression (likely supplier/input cost pressure), with a smaller labor-cost contribution and a mix effect from lower-margin online growth — not a revenue or demand problem, since top-line held flat.'},
  ],
  recommendationCriteria:{ mustAddress:['the COGS cost increase specifically, not generic cost-cutting','whether online growth at lower margin is a strategic tradeoff worth keeping'],
    strongAnswerLooksLike:'Renegotiate supplier terms / diversify sourcing to address the 6pp COGS increase directly; address overtime-driven labor cost through scheduling efficiency; treat online margin as an acceptable strategic tradeoff only if paired with a plan to improve online unit economics over time — not a blanket price increase or store closures.',
    conclusion:'conditional' },
  interviewerNotes:'Strong candidates isolate COGS as the dominant driver (6pp = $48M, more than the entire margin decline) before touching labor or mix. Weak candidates jump to "cut costs" or "raise prices" without isolating which cost moved.',
  gradingEvidence:{ opening:['problemDefinition'], structure:['structuring','prioritization'], exploration:['hypothesisDriven','exhibitInterpretation','businessJudgment','quantitativeReasoning'], synthesis:['synthesis'], recommendation:['recommendation'] },
  idealInsights:['COGS margin expansion, not labor or mix, is the dominant driver of the decline.','Online growth is a real but secondary margin drag, not the root cause.'],
  commonMistakes:['Recommending across-the-board cost cuts without isolating COGS as the driver.','Treating flat revenue as evidence of a demand problem.','Missing that price rose 8% while volume fell 12% — a real signal worth investigating, not just a footnote.'],
},
{
  id:'market-entry', label:'Market Entry', caseType:'market-entry', difficulty:'Intermediate', estimatedMin:28,
  supportedFirmStyles:['general','mckinsey','bcg','bain','oliverWyman'],
  title:'EV Charging Market Entry', industry:'Energy & Transportation',
  description:'A major oil company with 4,000 gas stations considers entering EV charging. Should they, and how?',
  prompt:'Our client is one of the largest petroleum companies in the US with $12B in annual revenue and a network of approximately 4,000 owned and operated gas stations. They are evaluating whether to enter the electric vehicle (EV) charging market. They want to know: should they enter, and if so, how and where?',
  objective:{ components:['determine whether to enter the EV charging market','if entering, recommend how and where to enter'],
    constraints:['US market','existing 4,000-station network as a potential asset'],
    successCriteria:'a clear go/no-go decision with a viable entry approach if yes' },
  hiddenFacts:[
    {id:'capital', category:'finance', fact:'The client has ~$800M in discretionary capital it is willing to deploy toward new growth initiatives over 3 years.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'brand', category:'market', fact:'Consumer surveys show mixed trust in the client\'s brand for EV charging, given its fossil-fuel association.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'regulation', category:'market', fact:'Federal infrastructure funding is available to offset a portion of charger installation costs at qualifying highway locations.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'internal-politics', category:'irrelevant', fact:'There is some internal executive disagreement about the initiative, but it is not a deciding factor for this analysis.', revealPolicy:'IRRELEVANT'},
  ],
  exhibits:[
    {id:'ex1', type:'line', title:'US EV Charging Market Size', revealPolicy:'PROACTIVELY_GIVEN', unit:'$B',
      data:{ xLabels:['Today','2027E','2030E'], series:[{label:'Market Size', values:[5,17,40]}] }, footnote:'~35% CAGR implied.', sourceNote:'Industry market research.'},
    {id:'ex2', type:'table', title:'Charger Economics', revealPolicy:'AVAILABLE_ON_REQUEST',
      data:{ columns:[{key:'type',label:'Charger Type'},{key:'cost',label:'Install Cost',unit:'$'},{key:'util',label:'Avg. Utilization',unit:'%'}],
        rows:[{type:'DC Fast', cost:'$50K–$200K', util:28},{type:'Level 2', cost:'$5K–$20K', util:'n/a (slower turnover)'}] }, sourceNote:'Industry benchmarks.'},
    {id:'ex3', type:'bar', title:'Competitive Landscape — Market Share', revealPolicy:'AVAILABLE_ON_REQUEST', unit:'%',
      data:{ categories:['Leading Network','2nd Player','3rd Player','All Others'], valueUnit:'%', series:[{label:'Share', values:[35,18,12,35]}] }, sourceNote:'Public network registration data.'},
  ],
  quantProblems:[
    {id:'q1', prompt:'If the client converts 400 of its highest-traffic stations to DC fast charging at an average install cost of $120K per station, what is the total capital required?', type:'numeric',
      correctAnswer:48000000, tolerancePct:3, unit:'$', relatedExhibitId:'ex2', competency:'quantitativeReasoning', requiresSoWhat:true,
      modelAnswer:'400 × $120K = $48M — well within the client\'s ~$800M discretionary capital, suggesting capital is not the binding constraint here.'},
  ],
  synthesisMoments:[
    {id:'s1', triggerPhase:'exploration', prompt:'Given the market growth and the client\'s existing footprint, what is your interim view on attractiveness?',
      idealSynthesis:'The market is genuinely attractive (35% CAGR, no dominant incumbent at 35% share), and the client\'s highway/suburban real estate is a real asset — but avg. 28% utilization and an unproven EV brand mean this is not a low-risk slam dunk; entry mode and location selection matter more than the go/no-go decision itself.'},
  ],
  recommendationCriteria:{ mustAddress:['whether the existing station network is a genuine advantage or just convenient real estate','a specific entry mode (build vs. partner) and location strategy, not a generic "enter cautiously"'],
    strongAnswerLooksLike:'Enter selectively at the highest-traffic highway locations using the existing real estate advantage, likely via a partnership with an established charging network to offset brand-trust risk and technical inexperience, rather than a full owned build-out — validate with a pilot at 50-100 stations before committing the full $800M.',
    conclusion:'conditional' },
  interviewerNotes:'A confident "yes, enter aggressively everywhere" without addressing utilization risk or brand mismatch is a weaker answer than a staged, partnership-first recommendation.',
  gradingEvidence:{ opening:['problemDefinition'], structure:['structuring'], exploration:['businessJudgment','exhibitInterpretation','hypothesisDriven'], synthesis:['synthesis'], recommendation:['recommendation','quantitativeReasoning'] },
  idealInsights:['The station network is a real but not sufficient advantage — brand trust and technical capability gaps remain.','28% average utilization is a real profitability risk that a naive "market is growing" story ignores.'],
  commonMistakes:['Recommending full-scale entry without addressing the utilization/profitability risk.','Treating the real-estate advantage as automatically decisive.','Ignoring competitive response from already-aggressive incumbents.'],
},
{
  id:'pricing', label:'Pricing', caseType:'pricing', difficulty:'Intermediate', estimatedMin:25,
  supportedFirmStyles:['general','mckinsey','bcg','bain','oliverWyman'],
  title:'Premium Meal-Kit Price Increase', industry:'Consumer / Direct-to-Consumer',
  description:'A premium meal-kit subscription company is considering a 12% price increase amid rising input costs.',
  prompt:'Our client runs a premium direct-to-consumer meal-kit subscription service, generating roughly $200M in annual revenue from about 2.2M boxes shipped per year at an average price of $90 per box. Rising ingredient and packaging costs have compressed margins, and leadership is considering a 12% across-the-board price increase. They want our recommendation on whether — and how — to raise prices.',
  objective:{ components:['determine whether a 12% price increase is advisable','recommend a specific pricing approach'],
    constraints:['premium DTC subscription model','12% is the increase currently under consideration'],
    successCriteria:'a clear pricing recommendation, including magnitude and approach, with a defensible rationale' },
  hiddenFacts:[
    {id:'contract', category:'operations', fact:'Customers are on a month-to-month subscription with no lock-in contract — they can cancel anytime.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'competitor', category:'market', fact:'The client\'s closest premium competitor has held prices flat through the same input-cost cycle.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'nps', category:'market', fact:'Net Promoter Score is 61, among the highest in the category, and has not moved in 18 months.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'churn-driver', category:'irrelevant', fact:'A recent app redesign received mixed reviews, but usage metrics show no material behavior change.', revealPolicy:'IRRELEVANT'},
  ],
  exhibits:[
    {id:'ex1', type:'table', title:'Prior Price Test Results (One Region, 9 Months Ago)', revealPolicy:'PROACTIVELY_GIVEN',
      data:{ columns:[{key:'metric',label:'Metric'},{key:'before',label:'Before'},{key:'after',label:'After'}],
        rows:[{metric:'Price per box', before:'$85', after:'$90 (+6%)'},{metric:'Monthly volume (region)', before:'50,000', after:'46,000 (-8%)'}] },
      sourceNote:'Regional price test, 9 months ago.'},
    {id:'ex2', type:'customerSegmentation', title:'Customer Segments by Price Sensitivity', revealPolicy:'AVAILABLE_ON_REQUEST',
      data:{ segments:[
        {label:'Convenience-Focused (low price sensitivity)', sharePct:55, metrics:{avgTenure:'14 months'}},
        {label:'Value-Conscious (high price sensitivity)', sharePct:45, metrics:{avgTenure:'6 months'}},
      ]}, sourceNote:'Customer survey + churn analysis.'},
    {id:'ex3', type:'bar', title:'Premium Meal-Kit Competitor Pricing', revealPolicy:'AVAILABLE_ON_REQUEST', unit:'$',
      data:{ categories:['Our Client','Competitor A','Competitor B'], valueUnit:'$/box', series:[{label:'Price per box', values:[90,88,95]}] }, sourceNote:'Public pricing pages.'},
  ],
  quantProblems:[
    {id:'q1', prompt:'The prior test showed a 6% price increase caused an 8% volume decline (implied elasticity ≈ -1.33). If that same elasticity holds for the proposed 12% increase, what is the expected % change in TOTAL REVENUE (not just price)? (negative if revenue falls)', type:'numeric',
      correctAnswer:-5.9, toleranceAbs:1.5, unit:'%', relatedExhibitId:'ex1', competency:'quantitativeReasoning', requiresSoWhat:true,
      modelAnswer:'Expected volume decline ≈ 12% × 1.33 ≈ 16%. Revenue multiplier = 1.12 × 0.84 ≈ 0.94 → revenue would likely FALL about 6%, not rise — the naive "raise price = raise revenue" assumption breaks at this elasticity.'},
  ],
  brainstormPrompts:[
    {id:'b1', prompt:'Beyond a blanket price increase, brainstorm other ways the client could improve profitability given rising input costs.', competency:'ideation',
      modelCategories:['Segmented/tiered pricing (raise price only for convenience-focused segment)','Cost reduction (ingredient sourcing, packaging)','Portion/recipe engineering to reduce input cost per box','Value-added upsells instead of raising the base price']},
  ],
  synthesisMoments:[
    {id:'s1', triggerPhase:'exploration', prompt:'After reviewing the prior price test and segmentation data, what is your interim view on a 12% increase?',
      idealSynthesis:'A uniform 12% increase is risky — the prior test\'s elasticity implies total revenue would likely fall, not rise. But the segmentation data suggests the risk isn\'t uniform: convenience-focused customers (55%, low sensitivity, longer tenure) could likely absorb a bigger increase than value-conscious customers (45%, high sensitivity, shorter tenure already).'},
  ],
  recommendationCriteria:{ mustAddress:['the elasticity math and why a uniform 12% increase is risky as proposed','a segmented or smaller alternative, not just "don\'t raise prices"'],
    strongAnswerLooksLike:'Recommend a smaller or segmented price increase — e.g., a larger increase for the convenience-focused segment and little-to-no increase for value-conscious/shorter-tenure customers — rather than a uniform 12% increase that the elasticity data suggests would shrink total revenue.',
    conclusion:'conditional' },
  interviewerNotes:'The case rewards candidates who actually run the elasticity math before recommending — a confident "raise prices, more revenue" without checking is the single most common mistake. Strong candidates immediately connect the segmentation data to a differentiated-pricing recommendation.',
  gradingEvidence:{ opening:['problemDefinition'], structure:['structuring'], exploration:['quantitativeReasoning','exhibitInterpretation','hypothesisDriven'], synthesis:['synthesis'], recommendation:['recommendation','ideation'] },
  idealInsights:['A uniform 12% increase likely REDUCES total revenue given the observed elasticity — the obvious move is wrong.','Segmentation data suggests a differentiated approach captures more value with less risk than a blanket increase.'],
  commonMistakes:['Recommending the full 12% increase without checking the implied revenue impact.','Ignoring the segmentation data when it directly informs a better-targeted recommendation.','Treating NPS/brand strength as proof pricing power exists without checking real elasticity evidence.'],
},
{
  id:'ma', label:'M&A', caseType:'ma', difficulty:'Advanced', estimatedMin:32,
  supportedFirmStyles:['general','mckinsey','bcg','bain','oliverWyman'],
  title:'Software Acquisition Decision', industry:'Technology',
  description:'An enterprise software firm considers acquiring a B2B SaaS startup at $800M. Worth it?',
  prompt:'Our client is a large enterprise software company with $5B in revenue serving Fortune 1000 firms. They are considering acquiring a B2B SaaS startup called Flowdesk, which provides project management and workflow automation tools. Flowdesk is privately held and asking $800M. The client needs to decide: should they acquire Flowdesk at this valuation, and if so, how should they integrate it?',
  objective:{ components:['determine whether to acquire Flowdesk at $800M','if acquiring, recommend an integration approach'],
    constraints:['$800M asking price','Flowdesk is privately held'],
    successCriteria:'a clear acquire/pass decision with strategic and financial justification' },
  hiddenFacts:[
    {id:'build-cost', category:'alternatives', fact:'Internal engineering estimates the client could build Flowdesk\'s core differentiating features in-house in ~18 months for roughly $40M.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'partner-option', category:'alternatives', fact:'Flowdesk\'s founders have also informally discussed a reseller/integration partnership as an alternative to a full sale.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'base-rate', category:'market', fact:'Industry studies suggest roughly 50-70% of enterprise software acquisitions fail to create positive shareholder value relative to the price paid.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'culture', category:'operations', fact:'Flowdesk\'s 120-person team is engineering-heavy with a fast-moving startup culture, a real contrast to the client\'s process-heavy enterprise culture.', revealPolicy:'PROACTIVELY_GIVEN'},
  ],
  exhibits:[
    {id:'ex1', type:'table', title:'Flowdesk Financial Snapshot', revealPolicy:'PROACTIVELY_GIVEN',
      data:{ columns:[{key:'metric',label:'Metric'},{key:'value',label:'Value'}],
        rows:[{metric:'ARR', value:'$50M'},{metric:'YoY Growth', value:'60%'},{metric:'Net Revenue Retention', value:'120%'},{metric:'EBITDA Margin', value:'-15%'},{metric:'Customers', value:'800'},{metric:'Avg. Contract Value', value:'$62K'}] },
      sourceNote:'Diligence data room.'},
    {id:'ex2', type:'pnl', title:'Client\'s Existing PM Module', revealPolicy:'AVAILABLE_ON_REQUEST', unit:'$',
      data:{ unit:'$', rows:[{label:'Revenue', value:120000000, isTotal:true}] }, footnote:'Growing only 5% YoY and increasingly losing competitive deals to Flowdesk.', sourceNote:'Internal segment reporting.'},
    {id:'ex3', type:'waterfall', title:'Estimated Deal Value Bridge', revealPolicy:'AVAILABLE_ON_REQUEST', unit:'$M',
      data:{ startLabel:'Flowdesk Standalone Value (10x ARR, category norm)', startValue:500,
        steps:[{label:'Cross-sell synergy (risk-adjusted)', delta:120},{label:'Cost synergy (G&A, infra)', delta:60},{label:'Integration/culture risk discount', delta:-80}],
        endLabel:'Risk-Adjusted Value Estimate' }, sourceNote:'Internal deal-team estimate (illustrative).'},
  ],
  quantProblems:[
    {id:'q1', prompt:'Cross-sell guidance is $30-50M in incremental ARR within 2 years. Assuming the midpoint ($40M) is realized at a 70% gross margin, what is the resulting annual gross profit from the synergy alone?', type:'numeric',
      correctAnswer:28000000, tolerancePct:5, unit:'$', relatedExhibitId:'ex3', competency:'quantitativeReasoning', requiresSoWhat:true,
      modelAnswer:'$40M × 70% = $28M in annual gross profit — against an $800M price, that\'s a >28-year payback on the synergy alone, meaning the deal is only justified if Flowdesk\'s standalone growth trajectory (not just the synergy) is worth the premium.'},
  ],
  synthesisMoments:[
    {id:'s1', triggerPhase:'exploration', prompt:'After reviewing Flowdesk\'s financials and the client\'s own PM module performance, what is your interim read on the strategic rationale?',
      idealSynthesis:'The strategic logic is real (Flowdesk is winning deals the client\'s own product is losing), but the $800M price (16x ARR) prices in both strong standalone growth AND synergy realization that history says is unreliable — the base rate on enterprise software M&A value creation is weak, and a build option exists at a fraction of the cost.'},
  ],
  recommendationCriteria:{ mustAddress:['the build-vs-buy-vs-partner comparison, not just a straight acquire/pass call','the base rate for M&A value creation and why this deal\'s price assumes optimistic synergy realization'],
    strongAnswerLooksLike:'Recommend NOT acquiring at $800M as structured — the price requires near-full synergy realization against a weak base rate, and a partnership or licensing arrangement (or, if speed matters less, an 18-month/$40M internal build) captures much of the strategic benefit at dramatically lower risk and cost; return to the table only at a meaningfully lower valuation.',
    conclusion:'no-go' },
  interviewerNotes:'This case is intentionally NOT a clean "yes, acquire" — a candidate who reasons carefully through the price, the synergy payback math, and the base rate should land on "pass at this price" or "pursue partner/build instead." A confident "yes, this is strategically compelling" without engaging the price/base-rate tension is a real gap, not just a different valid opinion.',
  gradingEvidence:{ opening:['problemDefinition'], structure:['structuring','prioritization'], exploration:['businessJudgment','quantitativeReasoning','hypothesisDriven','exhibitInterpretation'], synthesis:['synthesis'], recommendation:['recommendation'] },
  idealInsights:['The synergy math alone doesn\'t justify the price — the deal requires believing in Flowdesk\'s standalone trajectory too.','A build or partner alternative exists at a fraction of the cost and risk.','The base rate for enterprise software M&A value creation is unfavorable and should weigh on confidence, not just the deal-specific story.'],
  commonMistakes:['Recommending "acquire" purely from strategic rationale without pricing discipline.','Not comparing the acquisition against build or partner alternatives.','Treating the cross-sell synergy guidance as certain rather than risk-adjusting it.'],
},
{
  id:'operations', label:'Operations', caseType:'operations', difficulty:'Intermediate', estimatedMin:28,
  supportedFirmStyles:['general','mckinsey','bcg','bain','oliverWyman'],
  title:'Manufacturing Plant Efficiency', industry:'Consumer Goods',
  description:'A production plant at 68% utilization with 4.2% defects needs to hit 90% / 1.5% in 18 months.',
  prompt:'Our client is a consumer goods manufacturer with $1.2B in annual revenue. Their flagship plant, responsible for 40% of total output, is running at 68% capacity utilization with a 4.2% defect rate. The industry best-in-class benchmark is 90% utilization and 1.5% defects. The COO has given the plant manager 18 months to reach those benchmarks or the plant faces downsizing.',
  objective:{ components:['identify the root causes of low utilization and high defect rates','recommend specific actions to reach 90% utilization and 1.5% defects within 18 months'],
    constraints:['18-month deadline','flagship plant cannot be shut down','benchmark targets: 90% utilization, 1.5% defect rate'],
    successCriteria:'reach 90% utilization and 1.5% defect rate within 18 months' },
  hiddenFacts:[
    {id:'headcount', category:'operations', fact:'The plant has not added headcount in 3 years despite production complexity increasing.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'maintenance', category:'operations', fact:'There is no predictive maintenance system in place — maintenance is purely reactive.', revealPolicy:'PROACTIVELY_GIVEN'},
    {id:'capex', category:'finance', fact:'The COO has pre-approved up to $15M in capex for this plant if the business case is clear.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'union', category:'irrelevant', fact:'The plant is non-unionized; labor relations are not a factor in this case.', revealPolicy:'IRRELEVANT'},
  ],
  exhibits:[
    {id:'ex1', type:'capacityUtilization', title:'Production Line Performance', revealPolicy:'PROACTIVELY_GIVEN',
      data:{ lines:[
        {label:'Line A', utilizationPct:85, defectPct:1.8, notes:'Best performer.'},
        {label:'Line B', utilizationPct:65, defectPct:4.5, notes:'HVAC failure causing temperature variance on heat-sensitive components.'},
        {label:'Line C', utilizationPct:55, defectPct:6.5, notes:'2005-vintage equipment; unplanned downtime averaging 18 hrs/month.'},
      ]}, sourceNote:'Plant operations reporting.'},
    {id:'ex2', type:'bar', title:'Changeover Time: Current vs. Benchmark', revealPolicy:'AVAILABLE_ON_REQUEST', unit:'hrs',
      data:{ categories:['Current (avg. all lines)','Industry Benchmark'], valueUnit:'hrs', series:[{label:'Changeover Time', values:[4.2,1.8]}] },
      footnote:'Root cause: manual calibration procedures not yet digitized.', sourceNote:'Time-motion study.'},
    {id:'ex3', type:'table', title:'Line C Downtime Breakdown (18 hrs/month avg.)', revealPolicy:'AVAILABLE_ON_REQUEST',
      data:{ columns:[{key:'cause',label:'Cause'},{key:'hrs',label:'Hours/Month'}], rows:[
        {cause:'Unplanned equipment failure', hrs:10}, {cause:'Changeover', hrs:5}, {cause:'Other', hrs:3},
      ]}, sourceNote:'Maintenance logs.'},
  ],
  quantProblems:[
    {id:'q1', prompt:'Blended utilization across the 3 lines today is 68% (Line A 85%, Line B 65%, Line C 55%, roughly equal capacity). The target is 90%. What is the required increase in PERCENTAGE POINTS (not percent change)?', type:'numeric',
      correctAnswer:22, toleranceAbs:1, unit:'pp', relatedExhibitId:'ex1', competency:'quantitativeReasoning', requiresSoWhat:true,
      modelAnswer:'90 − 68 = 22 percentage points. Given Line A is already near-benchmark, nearly all of that gain has to come from Lines B and C — meaning the HVAC and equipment-age issues are not side notes, they are the core of the 18-month plan.'},
  ],
  synthesisMoments:[
    {id:'s1', triggerPhase:'exploration', prompt:'After reviewing line-level performance and the changeover data, what is your interim synthesis?',
      idealSynthesis:'This is not one problem — Line B\'s issue (HVAC) is a discrete, fixable equipment fault; Line C\'s issue (aging equipment, high unplanned downtime) is more structural; and the 4.2h vs. 1.8h changeover gap affects ALL lines equally and is the single highest-leverage common fix, since digitizing calibration alone could close a meaningful share of the 22pp gap plant-wide.'},
  ],
  recommendationCriteria:{ mustAddress:['distinct root causes per line, not one blanket fix','the changeover-time gap as a common, high-leverage, relatively low-cost fix'],
    strongAnswerLooksLike:'Prioritize digitizing the changeover/calibration procedure first (affects all lines, fastest payback, within the pre-approved capex), fix the Line B HVAC fault (clear, bounded cost), and evaluate Line C equipment replacement vs. continued reactive maintenance given its age and the 18-month window — a single "improve efficiency" recommendation without differentiating the 3 lines is a weaker answer.',
    conclusion:'conditional' },
  interviewerNotes:'Strong candidates immediately notice the 3 lines have 3 different root causes and refuse to recommend one blanket fix.',
  gradingEvidence:{ opening:['problemDefinition'], structure:['structuring','prioritization'], exploration:['exhibitInterpretation','businessJudgment','quantitativeReasoning'], synthesis:['synthesis'], recommendation:['recommendation'] },
  idealInsights:['The 3 lines have 3 distinct root causes — a single fix will not close the gap.','Changeover-time digitization is the highest-leverage common fix across all lines.'],
  commonMistakes:['Recommending a single blanket "efficiency improvement" program instead of line-specific fixes.','Not noticing that Line A is already near-benchmark and doesn\'t need the same intervention.','Ignoring the changeover-time data as a lower-priority detail.'],
},
{
  id:'growth', label:'Growth Strategy', caseType:'growth', difficulty:'Advanced', estimatedMin:32,
  supportedFirmStyles:['general','mckinsey','bcg','bain','oliverWyman'],
  title:'Regional Bank Revenue Growth', industry:'Financial Services',
  description:'A regional bank growing at 2% needs a path to 7% revenue growth in 3 years — with two segments telling different stories.',
  prompt:'Our client is a regional bank headquartered in Atlanta with $20B in assets and operations across six states in the Southeast US. They have grown revenue at approximately 2% per year, well below the regional banking industry average of 5% and their own target of 7%. The new CEO has engaged us to identify the best path to 7% revenue growth within three years.',
  objective:{ components:['identify the best path to 7% annual revenue growth','deliver growth within three years'],
    constraints:['Southeast US six-state footprint','three-year timeframe','7% revenue growth target'],
    successCriteria:'achieve 7% annual revenue growth within three years' },
  hiddenFacts:[
    {id:'mortgage', category:'market', fact:'The client has never entered the mortgage market, a gap versus most peer banks.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'geography', category:'market', fact:'Peer banks have expanded into fast-growing secondary cities; the client\'s footprint is concentrated in its existing metro markets.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'relationship-managers', category:'operations', fact:'Three senior commercial relationship managers left for a competitor in the past 18 months, taking several key client relationships with them.', revealPolicy:'AVAILABLE_ON_REQUEST'},
    {id:'branding', category:'irrelevant', fact:'The bank recently refreshed its logo and branding; this has not measurably affected any segment\'s performance.', revealPolicy:'IRRELEVANT'},
  ],
  exhibits:[
    {id:'ex1', type:'table', title:'Revenue by Segment', revealPolicy:'PROACTIVELY_GIVEN',
      data:{ columns:[{key:'seg',label:'Segment'},{key:'rev',label:'Revenue',unit:'$'},{key:'growth',label:'YoY Growth',unit:'%'}], rows:[
        {seg:'Retail Banking', rev:480000000, growth:1}, {seg:'Commercial Banking', rev:240000000, growth:-3}, {seg:'Wealth Management', rev:80000000, growth:15},
      ]}, sourceNote:'Segment financial reporting.'},
    {id:'ex2', type:'bar', title:'Digital Banking Adoption: Client vs. Peers', revealPolicy:'AVAILABLE_ON_REQUEST', unit:'%',
      data:{ categories:['Our Client','Peer Average'], valueUnit:'%', series:[{label:'Digital Adoption', values:[40,68]}] },
      footnote:'The adoption gap correlates with higher branch servicing costs and slower retail growth.', sourceNote:'Internal + industry benchmark data.'},
    {id:'ex3', type:'table', title:'Commercial Banking: Client Attrition Detail', revealPolicy:'AVAILABLE_ON_REQUEST',
      data:{ columns:[{key:'driver',label:'Driver of Commercial Decline'},{key:'share',label:'Share of Lost Revenue',unit:'%'}], rows:[
        {driver:'Clients following departed relationship managers to competitor', share:65}, {driver:'General market/rate competition', share:20}, {driver:'Other', share:15},
      ]}, footnote:'This is a genuinely SEPARATE driver from the retail segment\'s digital gap — commercial clients rely on relationship bankers, not digital channels.', sourceNote:'Client attrition analysis.'},
  ],
  quantProblems:[
    {id:'q1', prompt:'Total revenue today is $800M ($480M retail + $240M commercial + $80M wealth). At a 7% CAGR, what would target revenue be in 3 years (nearest $10M)?', type:'numeric',
      correctAnswer:980000000, tolerancePct:2, unit:'$', relatedExhibitId:'ex1', competency:'quantitativeReasoning', requiresSoWhat:true,
      modelAnswer:'$800M × 1.07³ ≈ $980M — roughly $180M of cumulative incremental revenue needed across all three segments over 3 years.'},
  ],
  brainstormPrompts:[
    {id:'b1', prompt:'Beyond fixing the two identified problems (digital gap, relationship-manager attrition), brainstorm additional growth levers the bank could pursue.', competency:'ideation',
      modelCategories:['Mortgage market entry','Geographic expansion into secondary cities','Wealth management scale-up (already growing 15%)','Digital-only product launch to close the adoption gap faster']},
  ],
  synthesisMoments:[
    {id:'s1', triggerPhase:'exploration', prompt:'Retail banking\'s digital gap and commercial banking\'s decline both need addressing — but are they the same problem? What is your interim synthesis?',
      idealSynthesis:'No — these are two DIFFERENT problems requiring different fixes. Retail\'s underperformance ties to the digital adoption gap (a real, addressable technology/UX investment). Commercial\'s decline is 65% driven by relationship-manager departures taking clients with them — a talent-retention and relationship-rebuilding problem that digital investment won\'t fix, since commercial clients aren\'t digital-sensitive. A single "invest in digital" recommendation would miss the larger, faster-moving commercial problem entirely.'},
  ],
  recommendationCriteria:{ mustAddress:['that retail and commercial declines have genuinely different root causes requiring different fixes','wealth management\'s already-strong growth as a segment to scale, not just fix problems elsewhere'],
    strongAnswerLooksLike:'A three-pronged plan: (1) close the digital adoption gap in retail banking, (2) rebuild commercial relationship-banking capacity and implement retention incentives for senior RMs — the higher-urgency fix given a 3-year clock and an ongoing bleed, (3) invest further in wealth management, the one segment already outgrowing the target. A recommendation that treats this as one unified "digital transformation" story misses the commercial banking evidence.',
    conclusion:'conditional' },
  interviewerNotes:'The two segment exhibits genuinely conflict with a single unifying "digital transformation" narrative — a strong candidate notices this and recommends distinct fixes per segment; a weaker candidate forces one story onto both.',
  gradingEvidence:{ opening:['problemDefinition'], structure:['structuring','prioritization'], exploration:['exhibitInterpretation','businessJudgment','hypothesisDriven','quantitativeReasoning'], synthesis:['synthesis'], recommendation:['recommendation','ideation'] },
  idealInsights:['Retail and commercial declines have genuinely different root causes — one narrative doesn\'t fit both.','Wealth management is already growing 15% and deserves continued investment, not just attention to the two problem segments.'],
  commonMistakes:['Forcing a single "digital transformation" narrative onto both retail and commercial declines.','Missing that commercial banking clients are relationship-driven, not digital-sensitive, so the same fix doesn\'t apply.','Ignoring wealth management entirely because it isn\'t a "problem" segment.'],
},
];

function getCaseConfig(type){ return CASES_CATALOG.find(c=>c.id===type)||CASES_CATALOG[0]; }
