// consultingContent/businessJudgment.js — Track: Business Judgment (6 modules)
CONSULTING_MODULES.push(
{
  id:'revenue-drivers', trackId:'businessJudgment', title:'Revenue Drivers', estimatedMinutes:7,
  primaryCompetency:'businessJudgment', secondaryCompetencies:['quantitativeReasoning'],
  prerequisites:[], concepts:['price x volume','revenue decomposition'],
  thinkFirst:{prompt:'A retailer\'s revenue fell 10%. Before any data, name the 3-4 most likely underlying drivers — not just "price and volume," go one level deeper.'},
  coreIdea:'Revenue = Price × Volume is the starting decomposition, but real business judgment means going one level deeper into WHY price or volume moved — traffic vs. conversion, new vs. existing customers, mix shift, discounting. Stopping at "price and volume" is a framework, not judgment.',
  badExample:{text:'"Revenue is down, so it\'s either price or volume." Then the candidate stops there and waits for data.', why:'This is true but useless — it doesn\'t generate any specific, testable hypothesis about WHAT actually happened to price or volume.'},
  strongExample:{text:'"If it\'s volume-driven, I\'d want to know if it\'s fewer customers, or the same customers buying less — that points to acquisition versus retention problems, which have completely different fixes. If it\'s price-driven, I\'d check whether it\'s a deliberate price cut, increased discounting, or a shift toward lower-priced products in the mix."', why:'Goes one level deeper into specific, distinguishable sub-drivers — each of which implies a different next step.'},
  explanation:'Keep a mental checklist one level below Price × Volume: for volume — new customers, existing customer frequency, existing customer basket size; for price — list price changes, discounting/promotions, product mix shift toward cheaper items.',
  exercise:{type:'text', prompt:'A subscription business\'s revenue grew but revenue PER CUSTOMER fell. Name 2 specific hypotheses for why, and what data would distinguish them.',
    modelAnswer:'Hypothesis 1: a pricing/plan mix shift — more customers are choosing a cheaper tier than before. Hypothesis 2: the customer base is diluting with newer, less-engaged customers who use fewer paid add-ons. Distinguishing data: plan-tier mix over time (tests hypothesis 1) versus usage/add-on attach rate by customer cohort/tenure (tests hypothesis 2).'},
  commonMistakes:['Stopping at "price or volume" without going deeper.','Not distinguishing between new-customer and existing-customer effects.','Ignoring product/segment mix shift as a distinct driver from price or volume itself.'],
  reusableRule:'Go one level below Price × Volume — ask which SPECIFIC sub-driver moved, since each implies a different fix.',
  nextDrillId:'profit-decline', relatedCaseIds:['profitability'], relatedFrameworkIds:[],
},
{
  id:'cost-drivers', trackId:'businessJudgment', title:'Cost Drivers', estimatedMinutes:7,
  primaryCompetency:'businessJudgment', secondaryCompetencies:['quantitativeReasoning'],
  prerequisites:['revenue-drivers'], concepts:['fixed vs variable cost','cost driver identification'],
  thinkFirst:{prompt:'A factory\'s per-unit cost rose 15% even though input material prices were flat. What are 2-3 specific hypotheses for why?'},
  coreIdea:'Costs move for reasons beyond "input prices went up" — volume/scale effects (spreading fixed costs over fewer units), efficiency/yield changes, and mix shift toward more expensive-to-produce items are all common, distinguishable drivers that generic "costs are fixed or variable" thinking misses.',
  badExample:{text:'"Per-unit cost is up, so probably input prices rose."', why:'The prompt explicitly says input prices were flat — the candidate offered the most generic possible hypothesis without engaging with the actual constraint given.'},
  strongExample:{text:'"If input prices are flat, I\'d look at volume — if production volume fell, fixed costs like factory overhead get spread over fewer units, raising per-unit cost mechanically even with nothing else changing. I\'d also check yield/scrap rates and whether the product mix shifted toward more labor-intensive items."', why:'Engages directly with the given constraint (flat input prices) and generates hypotheses that are actually consistent with it — volume/fixed-cost spreading, yield, and mix.'},
  explanation:'A quick mental checklist for rising per-unit cost with flat input prices: (1) lower volume spreading fixed costs thinner, (2) declining yield/efficiency, (3) product mix shift toward costlier items, (4) new costs entering that weren\'t there before (e.g., overtime, expedited shipping).',
  exercise:{type:'text', prompt:'A hospital\'s cost per patient visit rose 22% while patient volume held flat. Input costs (supplies, drugs) were flat too. Name 2 specific hypotheses.',
    modelAnswer:'Hypothesis 1: rising labor costs — overtime, agency/temp staffing, or wage increases — that wouldn\'t show up in "input costs" as typically defined. Hypothesis 2: a mix shift toward more complex/resource-intensive visit types (e.g., more specialist consults per visit) even though total visit COUNT held flat.'},
  commonMistakes:['Defaulting to "input prices rose" even when the prompt rules it out.','Not considering fixed-cost-spreading effects when volume changes.','Ignoring labor cost as a distinct category from material/input cost.'],
  reusableRule:'When input prices are ruled out, check volume/fixed-cost spreading, yield, mix shift, and labor cost separately.',
  nextDrillId:'profit-decline', relatedCaseIds:['profitability','operations'], relatedFrameworkIds:[],
},
{
  id:'pricing-power-judgment', trackId:'businessJudgment', title:'Pricing Power', estimatedMinutes:7,
  primaryCompetency:'businessJudgment', secondaryCompetencies:['quantitativeReasoning'],
  prerequisites:['cost-drivers'], concepts:['pricing power','willingness to pay','elasticity'],
  thinkFirst:{prompt:'A company is considering a 10% price increase. What are the 2-3 most important things you\'d want to know before assessing whether this is safe?'},
  coreIdea:'Pricing power — the ability to raise price without losing disproportionate volume — comes from being hard to substitute: differentiation, switching costs, brand, or a genuine lack of good alternatives. Judging a price increase means assessing WHY customers currently pay this price, not just whether the company "needs" more revenue.',
  badExample:{text:'"The company needs more revenue, so raising prices makes sense."', why:'This reasons from the COMPANY\'s need, not from the CUSTOMER\'s willingness to pay or available alternatives — the two things that actually determine whether a price increase will stick.'},
  strongExample:{text:'"I\'d want to know: how differentiated is this product versus competitors — do customers have easy substitutes? What\'s the customer\'s switching cost? And has the company tested smaller price moves before — what happened to volume then? Those three tell me whether 10% is safe or risky."', why:'Focuses on the actual determinants of pricing power — differentiation, switching costs, and empirical evidence from past price moves — rather than the company\'s internal need for revenue.'},
  explanation:'Signals of real pricing power: customers have few good substitutes, switching costs are high, the brand carries genuine premium value, or past price increases showed low volume sensitivity. Signals of WEAK pricing power: commodity product, low switching costs, price-sensitive customer base, aggressive competitors.',
  exercise:{type:'text', prompt:'A regional ISP with little local competition is considering a price increase. Name one reason it likely has real pricing power, and one risk that could undermine it.',
    modelAnswer:'Reason for pricing power: high switching costs and limited local competition mean customers may have few practical alternatives. Risk: if a new competitor (e.g., a new fiber or 5G home internet provider) enters the region, the pricing power could evaporate quickly, and pricing history (having room to compete downward) becomes a disadvantage instead of an advantage.'},
  commonMistakes:['Justifying a price increase based on the company\'s needs rather than the customer\'s alternatives.','Ignoring competitive response as a risk to a pricing move.','Treating "premium brand" as automatic pricing power without evidence.'],
  reusableRule:'Judge pricing power by customer substitutes and switching costs — not by how much the company needs the revenue.',
  nextDrillId:'profit-decline', relatedCaseIds:['profitability'], relatedFrameworkIds:[],
},
{
  id:'capacity-utilization', trackId:'businessJudgment', title:'Capacity and Utilization', estimatedMinutes:7,
  primaryCompetency:'businessJudgment', secondaryCompetencies:['quantitativeReasoning'],
  prerequisites:['pricing-power-judgment'], concepts:['capacity constraint','utilization rate'],
  thinkFirst:{prompt:'A hotel is 92% full most nights but revenue growth has stalled. What\'s the connection between those two facts?'},
  coreIdea:'When a business operates near full capacity, VOLUME growth naturally stalls regardless of demand — the constraint isn\'t sales or marketing, it\'s physical throughput. Recognizing a capacity constraint changes the whole set of relevant levers (pricing, expansion, efficiency) versus a demand problem (marketing, product, retention).',
  badExample:{text:'"Revenue growth stalled, so maybe marketing isn\'t working as well as it used to."', why:'Missed the capacity signal entirely — at 92% occupancy, there\'s very little ROOM left to sell more rooms regardless of how good marketing is; the growth constraint is physical, not demand-side.'},
  strongExample:{text:'"At 92% occupancy, there\'s almost no spare capacity — that likely explains the stalled revenue growth on its own, independent of demand. The lever here isn\'t more marketing, it\'s either raising price (since demand clearly exceeds supply) or physically expanding capacity."', why:'Correctly identifies capacity, not demand, as the binding constraint, and names the levers that actually fit a capacity-constrained situation.'},
  explanation:'A useful check: is utilization near 100%? If yes, growing volume further requires adding capacity (expensive, slow) or shifting toward price (fast, no capex) — marketing/demand-generation levers are largely wasted effort in a capacity-constrained business.',
  exercise:{type:'text', prompt:'A specialty manufacturer runs its single factory at 96% utilization and just turned down two new large orders. What would you recommend they consider, given the capacity constraint?',
    modelAnswer:'With near-full utilization and turned-away demand, consider raising prices (since demand clearly exceeds supply, at least for now) and/or evaluating capacity expansion (a second shift, added equipment, or a new facility) — the priority is figuring out whether the excess demand is durable enough to justify the capital cost of expanding, versus capturing more margin per unit via price in the meantime.'},
  commonMistakes:['Diagnosing a capacity-constrained situation as a demand or marketing problem.','Recommending demand-generation spend when the real constraint is physical throughput.','Not considering price as the fast, low-capex lever when capacity is the binding constraint.'],
  reusableRule:'Check utilization before diagnosing a growth problem — near-full capacity changes the entire set of relevant levers.',
  nextDrillId:'profit-decline', relatedCaseIds:['operations'], relatedFrameworkIds:[],
},
{
  id:'customer-segmentation-judgment', trackId:'businessJudgment', title:'Customer Segmentation', estimatedMinutes:7,
  primaryCompetency:'businessJudgment', secondaryCompetencies:['structuring'],
  prerequisites:['capacity-utilization'], concepts:['customer segmentation','average masking variation'],
  thinkFirst:{prompt:'Average customer satisfaction is flat at 4.2/5 for two years. What could be hiding underneath that flat average?'},
  coreIdea:'An average across the whole customer base can hide dramatically different stories in different segments — a flat average might mean genuinely nothing is changing, or it might mean one segment is improving while another deteriorates, with the two effects canceling out. Segmenting before trusting an average is a core business-judgment habit.',
  badExample:{text:'"Satisfaction is flat at 4.2, so customer experience isn\'t the issue."', why:'Trusts a single blended average without checking whether it\'s masking offsetting trends in different segments — a common trap that leads to dismissing a real, segment-specific problem.'},
  strongExample:{text:'"Before ruling out customer experience, I\'d want to segment that 4.2 average — by customer tenure, by product line, or by acquisition channel — since a flat blended average could easily be hiding a segment that\'s declining sharply, offset by another that\'s improving."', why:'Doesn\'t trust the average at face value and names specific, useful ways to segment it before drawing a conclusion.'},
  explanation:'Good default segmentation cuts: new vs. existing customers, high-value vs. low-value, by channel/geography, by product line. Whenever a metric looks surprisingly flat or stable, that\'s often itself a signal to segment, not a reason to stop looking.',
  exercise:{type:'text', prompt:'A retailer\'s overall same-store sales are flat. Name 2 ways you\'d segment this to check whether the flat average is hiding something.',
    modelAnswer:'Segment by store format or size (e.g., urban flagship vs. suburban) and by customer cohort (new vs. loyal/repeat) — a flat blended average could hide, for example, urban stores declining while suburban stores grow, or new customer spend falling while loyal customer spend rises to compensate.'},
  commonMistakes:['Treating an average as automatically representative of the whole business.','Not proposing specific, useful segmentation cuts (just saying "we should segment this").','Segmenting arbitrarily rather than along dimensions likely to reveal something actionable.'],
  reusableRule:'A flat or stable average is a reason to segment, not a reason to stop investigating.',
  nextDrillId:'profit-decline', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'competitive-response', trackId:'businessJudgment', title:'Competitive Response', estimatedMinutes:7,
  primaryCompetency:'businessJudgment', secondaryCompetencies:['recommendation'],
  prerequisites:['customer-segmentation-judgment'], concepts:['competitive response','second-order effects'],
  thinkFirst:{prompt:'You recommend the client cut prices 15% to win back share. What\'s the most important second-order effect you should think through before finalizing that recommendation?'},
  coreIdea:'Any recommendation that changes the competitive landscape — a price cut, an aggressive expansion, an acquisition — will likely provoke a RESPONSE from competitors, and a strong recommendation accounts for that response rather than assuming a static world where only the client moves.',
  badExample:{text:'"Cut price 15%, we\'ll win back the share we lost." No mention of what competitors might do next.', why:'Assumes competitors sit still — a price cut is highly visible and easy for competitors to match, and if they do, the client just gave up margin for nothing, ending up in the same relative position but less profitable.'},
  strongExample:{text:'"I\'d recommend the price cut cautiously — competitors, especially if they have similar cost structures, could likely match it within weeks, in which case we\'d have traded margin for no real share gain. I\'d want to also consider a differentiation-based move that\'s harder to directly match, or at least model the scenario where competitors DO match."', why:'Explicitly reasons through the likely competitive response and adjusts the recommendation\'s confidence and framing accordingly, rather than treating the recommendation as final without it.'},
  explanation:'Before finalizing any recommendation, ask: "if I were the competitor, how would I respond to this move — and does my recommendation still make sense if they do?" Moves that are easy to match (price) are riskier than moves that are hard to match (genuine product/service differentiation, exclusive relationships).',
  exercise:{type:'text', prompt:'You recommend a company launch an aggressive new-market expansion into a competitor\'s home territory. What competitive response should you consider, and how might it change your recommendation?',
    modelAnswer:'The incumbent competitor may respond with an aggressive price cut or promotional spend specifically in the contested region to defend share, potentially escalating into a costly regional price war. This might change the recommendation toward a more targeted, less visible entry (e.g., a specific underserved segment or channel) rather than a broad frontal assault likely to trigger a strong defensive reaction.'},
  commonMistakes:['Recommending a move as if competitors are static.','Only considering the client\'s own costs/benefits, not the competitive dynamic.','Not distinguishing between moves that are easy versus hard for competitors to match.'],
  reusableRule:'Before finalizing a recommendation, ask how a competitor would likely respond — and whether the recommendation still holds if they do.',
  nextDrillId:'profit-decline', relatedCaseIds:['market-entry','ma'], relatedFrameworkIds:[],
},
);
