// consultingContent/caseManagement.js — Track: Case Management (4 modules)
CONSULTING_MODULES.push(
{
  id:'asking-for-right-data', trackId:'caseManagement', title:'Asking for the Right Data', estimatedMinutes:6,
  primaryCompetency:'caseManagement', secondaryCompetencies:['hypothesisDriven'],
  prerequisites:[], concepts:['data requests','what would you ask next'],
  thinkFirst:{prompt:'You\'ve structured a profit decline into revenue and cost branches. What\'s the FIRST specific piece of data you\'d ask for, and why that one first?'},
  coreIdea:'Asking for data should be driven by your hypothesis and prioritization, not by working mechanically through your structure top to bottom. The strongest candidates ask for the piece of data that would most efficiently confirm or rule out their leading hypothesis — not just "the next item on the list."',
  badExample:{text:'"Can I see the revenue breakdown? ...Okay, now can I see the cost breakdown? ...Now can I see the customer data?" — requested in structure order with no stated reason.', why:'Mechanically working through the structure instead of prioritizing by what would be most INFORMATIVE given the current hypothesis — wastes time getting data that may not matter.'},
  strongExample:{text:'"Since my leading hypothesis is that this is a cost problem specifically in labor, I\'d like to see labor cost per store over time first — that would most directly confirm or rule out my hypothesis before I look at anything else."', why:'Ties the specific data request directly to the current hypothesis and explains why THIS piece of data, first, is the most efficient use of limited case time.'},
  explanation:'Before requesting data, complete the sentence: "I\'m asking for this because it would tell me whether ___ is true." If you can\'t complete that sentence, you\'re asking out of habit, not hypothesis.',
  exercise:{type:'text', prompt:'Your hypothesis is that a restaurant chain\'s traffic decline is concentrated in a specific daypart (e.g., breakfast). What data would you ask for first, and why?',
    modelAnswer:'"I\'d ask for traffic or sales broken down by daypart (breakfast/lunch/dinner) over the relevant period — that data would directly confirm or rule out whether the decline is concentrated in one daypart, which is exactly what my hypothesis predicts."'},
  commonMistakes:['Requesting data mechanically in structure order rather than by hypothesis priority.','Asking for data with no stated reason for why it matters.','Requesting overly broad data dumps instead of the specific cut that tests the hypothesis.'],
  reusableRule:'Every data request should complete: "I\'m asking for this because it would tell me whether ___ is true."',
  nextDrillId:'client-question', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'recovering-when-stuck', trackId:'caseManagement', title:'Recovering When Stuck', estimatedMinutes:7,
  primaryCompetency:'caseManagement', secondaryCompetencies:['communication'],
  prerequisites:['asking-for-right-data'], concepts:['recovering from mistakes','handling hints'],
  thinkFirst:{prompt:'Midway through a case, you realize you genuinely don\'t know how to proceed. What do you say — out loud, right now?'},
  coreIdea:'Getting stuck happens to every candidate, including strong ones — what separates a good recovery from a bad one is whether you narrate your thinking and ask for a specific kind of help, rather than going silent or freezing.',
  badExample:{text:'Candidate goes quiet for 20+ seconds, staring at their notes, saying nothing.', why:'Silence gives the interviewer zero information about whether the candidate is productively thinking or completely lost — and it\'s uncomfortable for everyone, which itself costs composure points.'},
  strongExample:{text:'"I want to think out loud for a second — I\'ve ruled out pricing and volume as clean explanations, so I\'m stuck on what else could explain the gap. Could you give me a hint about which part of the business to look at, or should I walk through my remaining hypotheses?"', why:'Narrates exactly where the confusion is, offers a specific way forward, and asks for a targeted hint rather than a vague "help me" — shows composure and structured thinking even while stuck.'},
  explanation:'When stuck, say precisely what you\'ve ruled out and what remains uncertain — that alone often unsticks you, since verbalizing narrows the problem. If it doesn\'t, ask a SPECIFIC question rather than a general "I don\'t know what to do."',
  exercise:{type:'text', prompt:'You\'re asked to estimate a market size and you\'ve frozen on what approach to take. Write what you\'d say out loud to recover.',
    modelAnswer:'"Let me think through this out loud — I could go top-down from total population, or bottom-up from unit economics per location. I\'ll go top-down since I have a rough sense of the population base to start from," then proceed — narrating the choice itself is often enough to break the freeze.'},
  commonMistakes:['Going silent for an extended period instead of narrating.','Asking for help too vaguely ("I don\'t know what to do") instead of specifically.','Panicking rather than treating being stuck as a normal, recoverable part of the process.'],
  reusableRule:'When stuck, narrate exactly what you\'ve ruled out and ask a specific question — never go silent.',
  nextDrillId:'client-question', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'managing-time', trackId:'caseManagement', title:'Managing Time', estimatedMinutes:6,
  primaryCompetency:'caseManagement', secondaryCompetencies:['prioritization'],
  prerequisites:['recovering-when-stuck'], concepts:['time management','knowing when to move on'],
  thinkFirst:{prompt:'You\'re 25 minutes into a 35-minute case and still in the exploration phase, with no recommendation yet. What do you do?'},
  coreIdea:'A case has a real time budget, and a strong candidate actively manages against it — noticing when a branch has produced enough insight to move on, and reserving enough time at the end for synthesis and recommendation, which are disproportionately weighted in most grading rubrics.',
  badExample:{text:'Candidate spends 30 of 35 minutes in exploration, leaving under 5 minutes to synthesize and recommend.', why:'Synthesis and recommendation are often the most heavily weighted parts of a case — running out of time for them, no matter how good the exploration was, caps the score.'},
  strongExample:{text:'"I\'m conscious we\'re getting toward the back half of our time — I think I have enough to form a recommendation now, so let me move to synthesizing what we\'ve found rather than exploring further."', why:'Proactively self-polices the time budget and prioritizes leaving room for synthesis/recommendation, which matter more to the final grade than one more round of exploration.'},
  explanation:'Rough time budget for a ~35-40 minute case: ~5 min opening/clarifying, ~5 min structuring, ~15-20 min exploration/analysis, ~5-8 min synthesis and recommendation. Check yourself against this budget periodically, out loud if useful.',
  exercise:{type:'text', prompt:'You notice you\'re 20 minutes into a 30-minute case, structure took longer than planned, and you haven\'t reached any data yet. What do you say?',
    modelAnswer:'"Given time, I want to move efficiently now — let me prioritize the single highest-value branch of my structure to explore, rather than going through all of them, so we have time to land on a recommendation."'},
  commonMistakes:['Losing track of time entirely and running out before reaching a recommendation.','Spending equal time on every branch regardless of the time remaining.','Rushing the recommendation so much it becomes shallow, rather than cutting exploration short instead.'],
  reusableRule:'Keep a rough time budget in mind and protect time for synthesis and recommendation — cut exploration short before you cut the ending short.',
  nextDrillId:'client-question', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'updating-hypothesis', trackId:'caseManagement', title:'Updating the Hypothesis', estimatedMinutes:6,
  primaryCompetency:'caseManagement', secondaryCompetencies:['hypothesisDriven'],
  prerequisites:['managing-time'], concepts:['updating hypotheses','maintaining direction'],
  thinkFirst:{prompt:'Your leading hypothesis was wrong — the data just ruled it out completely. What do you say in the next breath?'},
  coreIdea:'A hypothesis being wrong is a normal, expected part of a well-run case — the skill being tested is whether you update it cleanly and immediately, using the new information to form a sharper next hypothesis, rather than clinging to the original guess or losing direction entirely.',
  badExample:{text:'Data clearly rules out the original hypothesis, but the candidate keeps trying to make it fit, or pivots to a completely unrelated random guess.', why:'Clinging to a disproven hypothesis reads as not listening to the data; pivoting to something unrelated reads as having no real reasoning process, just guessing.'},
  strongExample:{text:'"Okay, that rules out my pricing hypothesis pretty clearly. Given what we just saw — that price and volume both held steady but total transactions fell — my new hypothesis is that we\'re losing customers outright, not selling less to the same customers. I\'d want to check customer count over time next."', why:'Explicitly acknowledges the disconfirmation, uses the SPECIFIC new evidence to build a sharper, related hypothesis, and states the next test.'},
  explanation:'Treat a disproven hypothesis as free information, not a setback — it eliminates a branch and narrows what remains. The new hypothesis should be built FROM the disconfirming evidence, not picked at random from what\'s left.',
  exercise:{type:'text', prompt:'Your hypothesis was that a product recall caused a sales drop, but data shows sales started falling two months BEFORE the recall. Update your hypothesis.',
    modelAnswer:'"That rules out the recall as the root cause, though it may have made things worse. Since sales started falling before the recall, I\'d now hypothesize something else changed two months prior — a competitor launch, a pricing change, or a distribution issue — and I\'d want to check what specifically happened around that earlier timeframe."'},
  commonMistakes:['Clinging to a disproven hypothesis instead of updating it.','Pivoting to a hypothesis unrelated to the new evidence.','Not explicitly acknowledging that the original hypothesis was wrong.'],
  reusableRule:'When a hypothesis is disproven, build the next one FROM the disconfirming evidence — don\'t discard the evidence with the hypothesis.',
  nextDrillId:'hyp-gen', relatedCaseIds:[], relatedFrameworkIds:[],
},
);
