// consultingContent/exhibits.js — Track: Exhibit Interpretation (4 modules)
// Each module now carries a real exhibit (consultingExhibits.js schema, rendered via the shared
// ExhibitViewer) matching the data already described in its thinkFirst/exercise text — added in
// Consulting Pass 2, replacing the text-only description from Pass 1.
CONSULTING_MODULES.push(
{
  id:'reading-charts', trackId:'exhibits', title:'Reading Charts', estimatedMinutes:8,
  exhibit:{id:'learn-ex-reading-charts', type:'line', title:'Quarterly Revenue by Product', revealPolicy:'PROACTIVELY_GIVEN', unit:'$M',
    data:{ xLabels:['Q1','Q2','Q3','Q4'], series:[{label:'Product A', values:[4,4.5,4.8,3.9]},{label:'Product B', values:[2,2.8,3.9,5.2]}] }},
  primaryCompetency:'exhibitInterpretation', secondaryCompetencies:['synthesis'],
  prerequisites:[], concepts:['headline first','chart interpretation'],
  thinkFirst:{prompt:'Data: Q1-Q4 revenue: Product A: $4M, $4.5M, $4.8M, $3.9M. Product B: $2M, $2.8M, $3.9M, $5.2M. In one sentence, what\'s the single most important insight?'},
  coreIdea:'When handed an exhibit, weak candidates read every number out loud in order. Strong candidates scan for the HEADLINE first — the one trend or comparison that matters most — and state that before diving into supporting detail.',
  badExample:{text:'"So Product A is 4, 4.5, 4.8, 3.9. Product B is 2, 2.8, 3.9, 5.2. Um... A grew then fell, B kept growing..."', why:'Narrating the raw numbers in order isn\'t interpretation — it makes the interviewer do the synthesis work the candidate was supposed to do.'},
  strongExample:{text:'"The headline is a crossover: Product B overtook Product A in Q4 after trailing all year, driven by consistent growth in B versus a Q4 decline in A. I\'d want to know what changed for A in Q4, and what\'s driving B\'s acceleration."', why:'Leads with the single most important pattern (the crossover), then immediately poses the next useful question — exactly what a real stakeholder wants from someone reading a chart for them.'},
  explanation:'Before saying anything, silently ask: what\'s changing, compared to what, and by how much? Only after you can answer that in one sentence should you start narrating specific numbers as supporting evidence.',
  exercise:{type:'text', prompt:'Data: customer acquisition cost by quarter: $40, $52, $68, $89. New customers per quarter: 10,000, 9,200, 8,100, 6,800. State the headline insight in one sentence.',
    modelAnswer:'CAC is rising sharply (more than doubled) while new customer volume is simultaneously falling — a worsening trend on both dimensions at once, suggesting whatever acquisition channel is being used is becoming both less efficient and less effective, not just more expensive for the same result.'},
  commonMistakes:['Reading numbers in table order instead of scanning for the pattern first.','Stating multiple "insights" with no sense of which one matters most.','Jumping to a recommendation before stating what the data actually shows.'],
  reusableRule:'Scan for the headline — what\'s changing, compared to what, by how much — before narrating any individual number.',
  nextDrillId:'chart-read', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'headline-evidence-implication', trackId:'exhibits', title:'Headline → Evidence → Implication', estimatedMinutes:8,
  exhibit:{id:'learn-ex-headline-evidence', type:'line', title:'COGS Margin Trend', revealPolicy:'PROACTIVELY_GIVEN', unit:'%',
    data:{ xLabels:['Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8'], series:[{label:'COGS Margin', values:[42,43.5,45,46.5,48,49,50,51]}] },
    footnote:'Gross revenue grew 18% over the same 8-quarter period (not plotted here).'},
  primaryCompetency:'exhibitInterpretation', secondaryCompetencies:['synthesis','recommendation'],
  prerequisites:['reading-charts'], concepts:['headline evidence implication','so what chain'],
  thinkFirst:{prompt:'Data: COGS margin went from 42% to 51% over 8 quarters while gross revenue grew 18%. Walk through Headline, then Evidence, then Implication in three short lines.'},
  coreIdea:'A complete exhibit read has three parts, always in this order: the HEADLINE (what\'s the pattern), the EVIDENCE (the specific numbers that support it), and the IMPLICATION (what does this mean for the case objective). Stopping after headline+evidence leaves the interviewer to do the last, most important step themselves.',
  badExample:{text:'"COGS margin rose from 42% to 51% over 8 quarters, even though revenue grew 18%." Then silence, waiting for the interviewer to ask "so what?"', why:'Headline and evidence are both present, but the candidate stopped short of the implication — the part that actually connects the data to the case objective.'},
  strongExample:{text:'"COGS margin rose from 42% to 51% over 8 quarters despite 18% revenue growth [evidence] — meaning the cost problem isn\'t about volume or scale, since revenue is growing fine [implication]. This points to a per-unit cost issue — input prices, supplier terms, or production efficiency — rather than a demand problem."', why:'Completes all three steps in one breath, ending on a specific, testable implication that directly points to the next branch of investigation.'},
  explanation:'Practice saying it as one flowing sentence with two hinges: "[headline], because [evidence], which means [implication]." If you can\'t complete the "which means" clause, you haven\'t actually finished interpreting the exhibit yet.',
  exercise:{type:'text', prompt:'Data: customer satisfaction scores held flat at 4.2/5 for two years, but customer churn rose from 8% to 15% over the same period. Write Headline, Evidence, Implication as three short phrases.',
    modelAnswer:'Headline: churn rose sharply despite stable satisfaction scores. Evidence: satisfaction flat at 4.2/5, churn up from 8% to 15%. Implication: whatever\'s driving churn probably isn\'t product/service quality (satisfaction didn\'t move) — more likely price, a competitive alternative, or a segment-specific issue satisfaction surveys aren\'t capturing.'},
  commonMistakes:['Stopping after headline and evidence without stating the implication.','Stating an implication that doesn\'t actually follow from the evidence.','Making the implication too vague to point toward a next step.'],
  reusableRule:'Every exhibit read completes all three: headline, evidence, implication — never stop at two.',
  nextDrillId:'chart-read', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'avoiding-over-calculation', trackId:'exhibits', title:'Avoiding Over-Calculation', estimatedMinutes:6,
  exhibit:{id:'learn-ex-over-calc', type:'pnl', title:'P&L — Profit Decline Diagnosis', revealPolicy:'PROACTIVELY_GIVEN', unit:'$M',
    data:{ unit:'$M', rows:[
      {label:'Revenue', value:420}, {label:'COGS', value:265}, {label:'Gross Profit', value:155, isSubtotal:true},
      {label:'G&A (incl. office, travel)', value:38}, {label:'Sales & Marketing', value:52}, {label:'R&D', value:41},
      {label:'Net Income', value:24, isTotal:true},
    ]}},
  primaryCompetency:'exhibitInterpretation', secondaryCompetencies:['prioritization'],
  prerequisites:['headline-evidence-implication'], concepts:['calculating only what matters'],
  thinkFirst:{prompt:'You\'re handed a table with 6 columns of data across 5 years. Before computing anything, what\'s the first question you should ask yourself?'},
  coreIdea:'Not every number in an exhibit needs to be calculated — the skill is identifying which 1-2 numbers, if computed, would actually change your recommendation, and ignoring the rest. Calculating everything wastes time and buries the signal in noise.',
  badExample:{text:'Given a table with revenue, cost, headcount, and margin by year for 5 years, the candidate computes year-over-year growth for every single column before saying anything.', why:'Most of that arithmetic doesn\'t bear on the case objective — it\'s busywork that delays the actual insight and burns limited case time.'},
  strongExample:{text:'"Given our objective is diagnosing the margin decline, the number I actually need is margin trend and its two components — I\'ll compute revenue growth and cost growth specifically, and skip headcount unless the first two don\'t explain the gap."', why:'Explicitly ties the choice of what to calculate back to the objective, and defers unnecessary computation unless it becomes relevant.'},
  explanation:'Before calculating, ask: "if I compute this and get answer X vs. answer Y, does my recommendation actually change?" If not, skip it — or note it as available but lower priority.',
  exercise:{type:'text', prompt:'You\'re given a P&L with 10 line items and asked to diagnose a profit decline. Name the 2 numbers you\'d compute FIRST, and one you\'d deliberately skip unless needed.',
    modelAnswer:'Compute first: revenue growth rate and gross margin trend — these two quickly tell you whether the problem is top-line or cost-driven. Skip initially: a detailed breakdown of G&A sub-line-items (e.g., office supplies, travel) — these rarely explain a material profit decline and are only worth digging into if the first two numbers don\'t explain the gap.'},
  commonMistakes:['Calculating every number in a table regardless of relevance.','Not stating why a particular number is worth calculating before starting.','Getting so absorbed in calculation that you lose track of the objective.'],
  reusableRule:'Before calculating anything, ask: would a different answer here actually change my recommendation? If not, skip it.',
  nextDrillId:'chart-read', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'multi-exhibit-synthesis', trackId:'exhibits', title:'Multi-Exhibit Synthesis', estimatedMinutes:8,
  exhibits:[
    {id:'learn-ex-multi-1', type:'line', title:'Market Growth Rate', revealPolicy:'PROACTIVELY_GIVEN', unit:'%',
      data:{ xLabels:['Yr 1','Yr 2','Yr 3'], series:[{label:'Market Growth', values:[8,10,12]}] }},
    {id:'learn-ex-multi-2', type:'line', title:'Client Market Share', revealPolicy:'PROACTIVELY_GIVEN', unit:'%',
      data:{ xLabels:['Yr 1','Yr 2','Yr 3'], series:[{label:'Client Share', values:[22,20,18]}] }},
  ],
  primaryCompetency:'exhibitInterpretation', secondaryCompetencies:['synthesis'],
  prerequisites:['avoiding-over-calculation'], concepts:['multi-chart synthesis','conflicting exhibits'],
  thinkFirst:{prompt:'Exhibit 1 shows market growth accelerating. Exhibit 2 shows the client\'s market share declining. How do you connect these two into one statement?'},
  coreIdea:'When multiple exhibits are revealed across a case, the highest-value skill is connecting them into ONE coherent story — not treating each as an isolated fact. Sometimes exhibits reinforce each other; sometimes they genuinely conflict, and noticing the conflict is itself an insight.',
  badExample:{text:'"Exhibit 1 shows the market is growing 12% a year. Exhibit 2 shows the client\'s share fell from 22% to 18%." Then the candidate moves to Exhibit 3 without connecting the two.', why:'Treats each exhibit as a separate fact instead of combining them — the real insight (the client is LOSING GROUND in a GROWING market, which is worse than losing ground in a shrinking one) never gets stated.'},
  strongExample:{text:'"Putting these together: the market itself is growing nicely, but the client is losing share within it — meaning competitors are capturing more of that growth than the client is. That\'s a more urgent problem than a shrinking market would be, since the client isn\'t just underperforming a bad environment, they\'re underperforming a GOOD one."', why:'Explicitly combines both exhibits into a single implication that\'s sharper and more actionable than either exhibit alone.'},
  explanation:'After each new exhibit, ask: "how does this change or confirm what I concluded from the LAST exhibit?" Keep a running one-sentence synthesis that updates as new data arrives, rather than a fresh, disconnected reaction each time.',
  exercise:{type:'text', prompt:'Exhibit 1: customer satisfaction is rising steadily. Exhibit 2: revenue per customer is falling steadily. Combine these into one synthesized insight.',
    modelAnswer:'Customers are happier but spending less — satisfaction and revenue are moving in opposite directions, which rules out "customers are unhappy and buying less" as the story, and instead points toward something like down-selling, reduced usage/consumption per customer, or a pricing/packaging change — worth investigating what changed in how customers are being served or charged, not the quality of service itself.'},
  commonMistakes:['Treating each exhibit as an isolated fact rather than updating a running synthesis.','Missing when two exhibits actually conflict, which is often the most important insight in the case.','Waiting until the very end to attempt synthesis instead of updating it continuously.'],
  reusableRule:'After every new exhibit, update one running sentence: how does this change what I concluded before?',
  nextDrillId:'chart-read', relatedCaseIds:[], relatedFrameworkIds:[],
},
);
