// consultingContent/fit.js — Track: Fit / Behavioral (8 modules)
// Uses the PARALLEL fit competency schema (FIT_COMPETENCY_IDS), not the primary 12 — see
// consultingCompetencies.js. Covers McKinsey-style PEI, Bain fit, BCG fit, and general
// consulting behavioral interviews as named contexts within the modules, not separate tracks.
CONSULTING_MODULES.push(
{
  id:'tell-me-about-yourself', trackId:'fit', title:'Tell Me About Yourself', estimatedMinutes:8,
  primaryCompetency:'storyStructure', secondaryCompetencies:['specificity','fitCommunication'],
  prerequisites:[], concepts:['narrative arc','elevator pitch'],
  thinkFirst:{prompt:'In 60 seconds, out loud (or in writing), answer "tell me about yourself" for a consulting interview. Don\'t read on until you\'ve tried it.'},
  coreIdea:'"Tell me about yourself" is not a biography — it\'s a 60-90 second narrative arc that connects your past experience to WHY consulting, told with a clear throughline, not a chronological list of jobs and schools.',
  badExample:{text:'"I grew up in Ohio, went to State University, majored in economics, then worked at a bank for two years doing analysis, and now I\'m applying to consulting because I want a new challenge."', why:'A chronological list with no throughline — doesn\'t explain WHY each step led to the next, and "a new challenge" is a generic, uncompelling reason for consulting specifically.'},
  strongExample:{text:'"I\'ve always been drawn to problems where the answer isn\'t obvious and you have to build the case for it yourself — that\'s what pulled me toward economics, then toward a banking analyst role where I got to advise clients on real capital decisions. What I found I loved most wasn\'t the finance itself, it was the structured problem-solving underneath it — which is exactly what pulled me toward consulting, where that\'s the whole job, across a much wider range of industries."', why:'Has a single throughline (drawn to ambiguous, structured problem-solving) that connects every stage and lands naturally on "why consulting" — not a list, a story with a point.'},
  explanation:'Pick ONE throughline before you start talking — a theme, value, or type of problem you\'re consistently drawn to — and select only the 2-3 experiences that best illustrate it. Everything else gets cut, even if it\'s impressive.',
  exercise:{type:'text', prompt:'Write a 3-sentence "tell me about yourself" with one clear throughline, ending on why consulting.',
    modelAnswer:'A strong answer names one consistent thread (e.g., "I\'m energized by taking ambiguous problems and building structure where none exists"), gives 1-2 concrete examples that show that thread in action, and closes by connecting that thread directly to what consulting actually is — not a generic "I want new challenges" statement.'},
  commonMistakes:['Listing experiences chronologically with no unifying theme.','Including too much detail on early/less relevant experiences.','Ending on a generic reason for consulting instead of one tied to the personal throughline just established.'],
  reusableRule:'Pick one throughline first, then choose only the 2-3 experiences that prove it — cut everything else.',
  nextDrillId:null, relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'why-consulting', trackId:'fit', title:'Why Consulting', estimatedMinutes:7,
  primaryCompetency:'authenticity', secondaryCompetencies:['specificity'],
  prerequisites:['tell-me-about-yourself'], concepts:['why consulting','avoiding generic answers'],
  thinkFirst:{prompt:'Answer "why consulting?" in 2 sentences — without using the words "smart people," "impact," or "interesting work."'},
  coreIdea:'"Why consulting" answers are graded partly on AVOIDING the three most generic reasons every candidate reaches for first (smart people, variety/impact, learning) — the strong version is personal and specific: a real moment or realization that makes the reason believable, not recited.',
  badExample:{text:'"I want to work with smart people on interesting problems and make a real impact across industries."', why:'This is the single most common answer interviewers hear, verbatim — it\'s not FALSE, but it\'s generic enough to be said by literally any candidate about literally any consulting firm, proving no real personal reflection happened.'},
  strongExample:{text:'"In my banking analyst role, the part I found most energizing wasn\'t the specific finance work, it was the handful of times I got pulled into a strategic question with no clear precedent — I want a career where THAT is the main event, not the exception, across a much wider range of problems than one industry allows."', why:'Grounds the answer in a specific, personal moment and names precisely what was energizing about it — believable and hard to have copy-pasted from generic advice.'},
  explanation:'Before answering, ask: "could literally any other candidate say this exact sentence?" If yes, go one level more specific — name an actual moment, project, or realization that makes the reason yours, not a category of reason.',
  exercise:{type:'text', prompt:'Write a "why consulting" answer grounded in one specific personal moment or realization, not a general category of reason.',
    modelAnswer:'A strong answer names a SPECIFIC moment (a project, a class, a realization) that revealed what the candidate actually wants from their work, and connects that directly and specifically to what consulting provides — avoiding "smart people / impact / learning" as the stated reason itself, even if those things are true.'},
  commonMistakes:['Leading with "smart people," "impact," or "interesting work" as the stated reason.','Giving an answer that could apply to literally any professional services career.','Not grounding the answer in any specific personal experience.'],
  reusableRule:'If any candidate could say your exact sentence, it\'s too generic — ground it in one specific personal moment.',
  nextDrillId:null, relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'why-this-firm', trackId:'fit', title:'Why This Firm', estimatedMinutes:7,
  primaryCompetency:'authenticity', secondaryCompetencies:['specificity'],
  prerequisites:['why-consulting'], concepts:['firm differentiation','why this firm not another'],
  thinkFirst:{prompt:'Answer "why McKinsey (or Bain, or BCG) specifically, and not one of the other two?" — the hardest version of this question, since it forces real differentiation.'},
  coreIdea:'"Why this firm" needs genuine differentiation FROM the other top firms, not generic praise that could apply to any of them — this requires specific research: people you\'ve spoken with, a practice area, a firm-specific program or culture element, not just "great reputation and smart people."',
  badExample:{text:'"McKinsey has an amazing reputation, works with top clients, and has smart, driven people."', why:'Every top firm has a strong reputation, top clients, and smart people — this gives the interviewer zero information about why THIS firm specifically, versus its closest competitors.'},
  strongExample:{text:'"Every conversation I\'ve had with McKinsey people, including two informational calls, kept coming back to a real depth of specialization in [specific practice area] that I didn\'t hear as strongly from other firms I spoke with — that\'s the kind of focused expertise I want to build, not just broad generalist exposure."', why:'Cites specific evidence (actual conversations, a specific practice area) that genuinely differentiates this firm from its closest peers, rather than generic praise.'},
  explanation:'Do the actual research: talk to 2-3 people at the firm if possible, and identify ONE specific thing (a practice area, a stated value that showed up in conversation, a program) that came up repeatedly and that you didn\'t hear as strongly elsewhere. That specific, evidenced difference is the answer.',
  exercise:{type:'text', prompt:'Without naming a real firm, write a template for a strong "why this firm" answer, noting what KIND of evidence it should cite.',
    modelAnswer:'A strong template cites a SPECIFIC, firsthand source of evidence (a conversation with an actual employee, a specific practice/program, a concrete experience during recruiting) that surfaced something genuinely differentiating about this firm versus its closest competitors — not adjectives (smart, prestigious, collaborative) that could describe any of them.'},
  commonMistakes:['Using adjectives that apply equally to every top firm.','Having done no real research beyond the firm\'s website.','Being unable to explain why NOT the firm\'s closest competitor.'],
  reusableRule:'Cite one specific, firsthand piece of evidence that differentiates this firm from its closest peers — not adjectives.',
  nextDrillId:null, relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'leadership-story', trackId:'fit', title:'Leadership Story', estimatedMinutes:8,
  primaryCompetency:'personalOwnership', secondaryCompetencies:['impact','storyStructure'],
  prerequisites:['why-this-firm'], concepts:['leadership story','STAR beyond the summary'],
  thinkFirst:{prompt:'Think of a real time you led something — even informally. In one sentence, what did YOU specifically do that someone else in your position might not have?'},
  coreIdea:'A leadership story needs to isolate what YOU specifically did — your individual decisions and actions — not what "the team" accomplished. Interviewers probe hard for this because vague team-credit answers are the single most common weakness in behavioral responses.',
  badExample:{text:'"Our team took on a big project, and we worked really hard and pulled together to deliver it on time, and I think that shows leadership."', why:'Entirely team-framed — "we" throughout, with no isolatable individual action. The interviewer can\'t tell what the candidate specifically contributed versus anyone else on the team.'},
  strongExample:{text:'"When our team\'s project stalled because two members disagreed on approach, I specifically set up a 1:1 with each of them to understand their concerns privately, then proposed a hybrid approach that addressed both — that\'s the moment I\'d call the leadership action, not just the team\'s overall effort."', why:'Isolates one specific decision and action the candidate personally took, with enough detail (the 1:1s, the hybrid proposal) to be clearly THEIRS, not the team\'s collective credit.'},
  explanation:'Before telling the story, identify the single MOMENT where you made a decision or took an action that someone else in your position might not have — that moment, described specifically, is the actual answer. Everything else is context.',
  exercise:{type:'text', prompt:'Think of a real leadership moment. Write ONE sentence isolating the specific decision or action YOU took (not "we").',
    modelAnswer:'A strong sentence uses "I" as the subject and names a specific, isolatable decision or action ("I proposed...", "I decided to...", "I pushed back on...") rather than describing outcomes the team achieved collectively.'},
  commonMistakes:['Using "we" throughout instead of isolating individual action.','Describing the outcome in detail but the individual decision vaguely.','Picking a story where the candidate\'s role was genuinely minor.'],
  reusableRule:'Isolate the one specific moment where YOU made a decision someone else might not have — that\'s the story.',
  nextDrillId:null, relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'conflict-story', trackId:'fit', title:'Conflict Story', estimatedMinutes:8,
  primaryCompetency:'reflection', secondaryCompetencies:['personalOwnership','specificity'],
  prerequisites:['leadership-story'], concepts:['conflict story','handling disagreement productively'],
  thinkFirst:{prompt:'Think of a real disagreement with a teammate, classmate, or coworker. What specifically did the OTHER person say or want, in their own words?'},
  coreIdea:'A strong conflict story shows you genuinely understanding the other side\'s perspective (not just describing your own frustration) and taking a concrete, specific action to resolve it — not just "we talked it out and things got better."',
  badExample:{text:'"A coworker and I disagreed on how to approach a project, but we talked about it and eventually found a compromise and it worked out fine."', why:'No detail on what the disagreement actually was, what the other person\'s perspective was, or what specific action resolved it — "we talked about it" tells the interviewer nothing about the candidate\'s actual conflict-resolution skill.'},
  strongExample:{text:'"My teammate wanted to prioritize speed to launch, while I was worried we\'d ship something broken — instead of arguing my position harder, I asked him to walk me through exactly what was driving the urgency, which turned out to be a specific client deadline I didn\'t know about. Once I understood that, I proposed we ship a scoped-down version by his deadline instead of the full version, which addressed both concerns."', why:'Names the other person\'s specific position, shows genuinely trying to understand WHY (not just what), and describes a concrete, specific resolution that addressed both sides — not a vague "we compromised."'},
  explanation:'The strongest conflict stories show a moment of genuinely UPDATING your understanding of the other person\'s position — not just holding firm until they gave in, and not just "agreeing to disagree." Name what you learned about their perspective that changed your approach.',
  exercise:{type:'text', prompt:'Think of a real disagreement. Write what the OTHER person\'s specific concern was (in one sentence), and what you did once you understood it.',
    modelAnswer:'A strong answer names the other person\'s underlying concern specifically (not just "they disagreed with me") and describes a concrete action taken as a direct result of understanding that concern — showing genuine perspective-taking, not just a negotiated truce.'},
  commonMistakes:['Describing only your own frustration, not the other person\'s actual position.','Ending on "we talked and it worked out" with no specific resolution described.','Choosing a story where you were simply right and the other person simply conceded.'],
  reusableRule:'Name the other person\'s specific concern, then the specific action you took once you understood it.',
  nextDrillId:null, relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'failure-story', trackId:'fit', title:'Failure Story', estimatedMinutes:8,
  primaryCompetency:'reflection', secondaryCompetencies:['personalOwnership','authenticity'],
  prerequisites:['conflict-story'], concepts:['failure story','genuine ownership'],
  thinkFirst:{prompt:'Think of a real failure — not a "weakness disguised as a strength." What did YOU specifically get wrong?'},
  coreIdea:'A strong failure story is a REAL failure with genuine personal ownership of what went wrong — not a humble-brag ("I worked too hard") and not a story where the failure was really someone else\'s fault. The reflection on what changed afterward matters as much as the failure itself.',
  badExample:{text:'"I guess my failure is that I care too much and sometimes take on too much work, which can lead to burnout."', why:'A classic humble-brag disguised as a weakness — it\'s not a real failure, and interviewers hear this exact answer constantly, which reads as evasive rather than reflective.'},
  strongExample:{text:'"I once assumed a client stakeholder was aligned with our recommendation because they hadn\'t objected in meetings, and didn\'t proactively check in one-on-one — it turned out they had real concerns they just weren\'t raising in the group setting, and the project stalled when it finally surfaced. Since then, I always do individual check-ins with key stakeholders before a group decision point, not just during it."', why:'A real, specific failure with clear personal ownership (the candidate\'s own assumption caused it), and a concrete, lasting change in behavior as a result — genuine reflection, not a deflection.'},
  explanation:'Pick a failure where YOU made a specific, identifiable mistake — not bad luck, not someone else\'s error, not a disguised strength. End with a concrete behavior change you\'ve actually kept doing since, not a vague lesson.',
  exercise:{type:'text', prompt:'Think of a real mistake you made. Write one sentence naming exactly what YOU got wrong, and one sentence on what you do differently now.',
    modelAnswer:'A strong answer names a specific, owned error ("I assumed X without checking," "I didn\'t ask for help when I should have") rather than a vague or externalized cause, and closes with a concrete, still-practiced behavior change, not just a stated lesson.'},
  commonMistakes:['Choosing a "weakness disguised as a strength" instead of a real failure.','Blaming external factors or other people for the failure.','Ending on a vague lesson ("I learned to communicate better") instead of a concrete behavior change.'],
  reusableRule:'Own a real, specific mistake — and close with a concrete behavior change you still practice, not a vague lesson.',
  nextDrillId:null, relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'impact-story', trackId:'fit', title:'Impact Story', estimatedMinutes:7,
  primaryCompetency:'impact', secondaryCompetencies:['specificity'],
  prerequisites:['failure-story'], concepts:['impact story','measurable results'],
  thinkFirst:{prompt:'Think of something you\'re proud of accomplishing. How would you MEASURE the impact — not just describe that it went well?'},
  coreIdea:'A strong impact story quantifies or concretely specifies the result — a number, a comparison, a before/after — rather than relying on adjectives like "successful" or "significant," which carry no verifiable information.',
  badExample:{text:'"I led a project that was really successful and had a big impact on the organization."', why:'"Successful" and "big impact" are adjectives with no verifiable content — the interviewer has no way to gauge whether this was a meaningful result or a minor one dressed up in strong language.'},
  strongExample:{text:'"I redesigned our club\'s onboarding process, which increased new-member retention from 40% to 68% over one semester, measured against the same metric the prior three semesters."', why:'Specific numbers (40% to 68%), a clear timeframe, and an explicit comparison baseline (prior semesters) — verifiable, concrete impact rather than a vague claim of success.'},
  explanation:'If you don\'t have an exact number, use the best available proxy: relative comparison ("faster than the team had ever done it before"), scope ("used by all 200 members," not just "widely used"), or a specific before/after contrast. Any of these beats an unquantified adjective.',
  exercise:{type:'text', prompt:'Think of something you accomplished. Write one sentence describing its impact with a specific number, comparison, or scope — not an adjective.',
    modelAnswer:'A strong sentence replaces "successful"/"significant"/"impactful" with a specific figure, percentage, comparison to a prior baseline, or concrete scope (how many people, how much time saved, how much revenue/cost affected).'},
  commonMistakes:['Relying on adjectives ("significant," "successful") instead of specifics.','Citing a number with no baseline or comparison to make it meaningful.','Choosing an accomplishment where impact genuinely can\'t be specified, without finding a proxy metric.'],
  reusableRule:'Replace every impact adjective with a number, comparison, or concrete scope — no exceptions.',
  nextDrillId:null, relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'handling-pei-followups', trackId:'fit', title:'Handling PEI Follow-Ups', estimatedMinutes:8,
  primaryCompetency:'handlingFollowUps', secondaryCompetencies:['specificity','personalOwnership'],
  prerequisites:['impact-story'], concepts:['PEI probing','follow-up pressure'],
  thinkFirst:{prompt:'You just told a leadership story. The interviewer asks: "What specifically did you say to them in that conversation?" How do you answer if you genuinely don\'t remember the exact words?'},
  coreIdea:'McKinsey-style PEI (Personal Experience Interview) and similar deep-probing formats push past your prepared summary with specific follow-ups — "what exactly did you say," "what did they say back," "why that approach and not another" — testing whether the story is real and deeply understood, not just rehearsed.',
  badExample:{text:'When pushed for specifics ("what did you actually say?"), the candidate gets flustered and restates the same summary in slightly different words.', why:'Restating the summary instead of going deeper signals the story may be more polished than genuinely remembered/lived — exactly what probing follow-ups are designed to detect.'},
  strongExample:{text:'"I don\'t remember my exact words, but the substance was — I told him I understood the deadline pressure but flagged that shipping without the fix risked a worse outcome for the client relationship long-term. He pushed back that leadership wanted speed, and I proposed we escalate together rather than me unilaterally deciding either way."', why:'Honestly acknowledges not remembering verbatim wording, but goes DEEPER into the substance and the back-and-forth — showing the memory is real and detailed, not just a rehearsed headline.'},
  explanation:'Prepare stories you know deeply enough to go 2-3 layers deeper than your rehearsed summary — know the other person\'s specific reaction, the alternative you considered and rejected, and the hardest moment. If a follow-up catches you short, be honest about not remembering exact wording, but supply real substance.',
  exercise:{type:'text', prompt:'After telling a conflict story, the interviewer asks "what alternative approach did you consider and reject?" Write a strong-format answer (doesn\'t need to be a real story).',
    modelAnswer:'A strong answer names a SPECIFIC alternative that was genuinely considered ("I thought about escalating to our manager immediately") and gives a specific reason it was rejected ("but I decided to try resolving it directly first since it hadn\'t reached that threshold yet") — showing real deliberation, not an invented afterthought.'},
  commonMistakes:['Restating the same summary when pushed for specifics instead of going deeper.','Getting visibly flustered by follow-up pressure instead of treating it as normal.','Inventing details on the spot that contradict the original story.'],
  reusableRule:'Know your stories 2-3 layers deeper than the rehearsed summary — the other person\'s reaction, the rejected alternative, the hardest moment.',
  nextDrillId:null, relatedCaseIds:[], relatedFrameworkIds:[],
},
);
