// consultingContent/fundamentals.js — Track: Case Fundamentals (5 modules)
CONSULTING_MODULES.push(
{
  id:'what-case-tests', trackId:'fundamentals', title:'What a Case Interview Tests', estimatedMinutes:6,
  primaryCompetency:'problemDefinition', secondaryCompetencies:['caseManagement'],
  prerequisites:[], concepts:['case interview purpose','candidate-led vs interviewer-led'],
  thinkFirst:{prompt:'Before reading on: what do you think a case interview is actually measuring? Write one sentence — not "problem solving," something more specific.'},
  coreIdea:'A case interview is not a test of business knowledge — it\'s a simulation of how you think under ambiguity with a colleague watching. The interviewer is grading your PROCESS (how you structure, prioritize, and reason) far more than your final answer, because on the job nobody hands you a clean problem statement.',
  badExample:{text:'A candidate hears "our client\'s profits are down" and immediately says "I think it\'s a cost problem, probably labor costs" — then tries to confirm that guess.', why:'This isn\'t hypothesis-driven thinking, it\'s pattern-matching to the first plausible story. It skips the step of actually defining what "profits are down" means before diagnosing it.'},
  strongExample:{text:'A candidate hears the same prompt and says "Before I dive in, let me make sure I understand the objective — are we trying to diagnose why profit fell, or are we deciding what to DO about it? And is there a specific target or timeframe?"', why:'This candidate is testing the boundaries of the problem before solving it — exactly what a real engagement requires before a team burns weeks on the wrong question.'},
  explanation:'Interviewers are trained to notice: did you clarify before diving in, did your structure follow logically from the objective, did you stay composed when the data contradicted your hypothesis, did you synthesize instead of just reciting numbers. None of that requires "knowing" the profitability framework by heart — it requires disciplined thinking you can build with practice.',
  exercise:{type:'text', prompt:'A friend tells you: "My startup\'s case interview coach said just memorize the frameworks and I\'ll be fine." In 2-3 sentences, explain what\'s wrong with that advice.',
    modelAnswer:'Frameworks are a scaffold, not the skill being tested. An interviewer can tell within a minute whether a candidate is reciting a memorized structure versus reasoning about THIS specific client\'s situation — memorized frameworks that don\'t connect to the actual objective read as generic and get penalized, not rewarded.'},
  commonMistakes:['Treating the case as a knowledge test to cram for rather than a thinking process to practice.','Assuming a "right answer" exists that the interviewer is hiding — most cases have several defensible recommendations.'],
  reusableRule:'You are being graded on how you think, not on what you already know — every action should make your reasoning visible.',
  nextDrillId:null, relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'listening-to-prompt', trackId:'fundamentals', title:'Listening to the Prompt', estimatedMinutes:6,
  primaryCompetency:'problemDefinition', secondaryCompetencies:['caseManagement'],
  prerequisites:['what-case-tests'], concepts:['active listening','note-taking'],
  thinkFirst:{prompt:'"Our client is a regional airline. Revenue is flat but costs are rising, and the CEO wants to know if they should cut routes." What are the 3 most important facts to write down before you say anything?'},
  coreIdea:'The prompt is read once, often fast, and contains every constraint you\'ll be graded on using correctly later. Weak candidates listen for the "topic" (airline, profitability). Strong candidates listen for the DECISION being asked, the ACTOR who has to make it, and any stated CONSTRAINTS or TIMEFRAME — and write them down verbatim.',
  badExample:{text:'Candidate writes down "airline, costs up, revenue flat" and launches into a profitability framework.', why:'This captures the topic but drops the actual decision ("should they cut routes") and who\'s asking (the CEO, implying a strategic not just diagnostic lens) — both of which change what a strong structure looks like.'},
  strongExample:{text:'Candidate writes: "DECISION: cut routes or not? CONTEXT: revenue flat, costs rising. WHO: CEO (strategic call, not just an audit)." Then restates it back before structuring.', why:'Capturing the decision, not just the topic, means every later branch of the structure can be tested against "does this help answer the actual question."'},
  explanation:'Most candidates can repeat the numbers from a prompt. Few can repeat the actual DECISION being asked. Train yourself to write three columns as you listen: Decision / Facts / Constraints — it forces you to parse the prompt for structure, not just content, in real time.',
  exercise:{type:'text', prompt:'"A hospital network\'s ER wait times have doubled in 18 months. The COO has 6 months before a state regulatory review and wants a fix." Write the Decision, Facts, and Constraints in three short lines.',
    modelAnswer:'DECISION: how to reduce ER wait times (an operational fix, not a market strategy). FACTS: wait times doubled over 18 months. CONSTRAINTS: 6-month deadline tied to a regulatory review — meaning speed and defensibility both matter, not just the optimal fix.'},
  commonMistakes:['Writing down numbers but not the decision.','Missing the actor/stakeholder, which often signals whether the case wants a strategic or operational answer.','Not writing anything down at all and trying to hold it all in memory.'],
  reusableRule:'Before structuring, write Decision / Facts / Constraints — three lines, every case, no exceptions.',
  nextDrillId:null, relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'clarifying-questions', trackId:'fundamentals', title:'Clarifying Questions', estimatedMinutes:7,
  primaryCompetency:'problemDefinition', secondaryCompetencies:['caseManagement'],
  prerequisites:['listening-to-prompt'], concepts:['clarifying questions','scoping'],
  thinkFirst:{prompt:'"Our client wants to grow revenue." Before structuring anything, what ONE clarifying question would narrow this the most?'},
  coreIdea:'Clarifying questions exist to remove genuine ambiguity that changes your structure — not to stall, and not to ask things you could reasonably assume. A good clarifying question, if answered differently, would send you down a materially different path.',
  badExample:{text:'"What industry is the client in? What\'s their revenue? How many employees do they have? What\'s their org structure?"', why:'A barrage of questions that don\'t change the structure — this reads as stalling and burns the interviewer\'s patience without producing any real scoping value.'},
  strongExample:{text:'"Is \'grow revenue\' the actual objective, or is there a target — like a specific percentage or timeframe — and should I assume organic growth is in scope, or are M&A and partnerships also on the table?"', why:'Each question, if answered differently, meaningfully changes the structure — target size changes urgency/scale, and inorganic-vs-organic scope changes which branches of the tree even belong.'},
  explanation:'Ask yourself, before voicing a question: "if the answer is A instead of B, does my structure actually change?" If not, don\'t ask it — note it as an assumption instead and move on. Two or three sharp questions beat ten generic ones.',
  exercise:{type:'text', prompt:'"A retailer wants to know if it should close its 40 lowest-performing stores." Write ONE clarifying question that would materially change your approach, and explain in one sentence why it matters.',
    modelAnswer:'"Are we optimizing purely for near-term profitability, or does the client care about brand presence/market share in those locations too?" — if the answer is pure profitability, the analysis is a straightforward store-level P&L; if brand/market presence matters, you need a completely different lens (e.g., flagship value, competitive signaling) layered on top.'},
  commonMistakes:['Asking questions with no bearing on the structure.','Asking so many questions the interviewer starts giving vague or annoyed answers.','Never stating assumptions for things you didn\'t ask about.'],
  reusableRule:'Only ask a clarifying question if a different answer would change your structure — otherwise state it as an assumption and move on.',
  nextDrillId:null, relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'defining-objective', trackId:'fundamentals', title:'Defining the Objective', estimatedMinutes:7,
  primaryCompetency:'problemDefinition', secondaryCompetencies:['communication'],
  prerequisites:['clarifying-questions'], concepts:['objective statement','decision-oriented framing'],
  thinkFirst:{prompt:'"Our client, a mid-size bank, is losing market share to fintech competitors and wants our help." State the case objective in one sentence, the way you\'d say it out loud to the interviewer.'},
  coreIdea:'A strong objective statement is decision-oriented (names the actual decision to be made), client-centered (about their goals, not a generic topic), and concise. It is the single sentence that every later branch of your structure should be testable against.',
  badExample:{text:'"So basically we\'re looking at market share and fintech competition for a bank."', why:'This restates the topic, not the decision. It gives the interviewer no signal that the candidate understands what they\'re actually being asked to solve for.'},
  strongExample:{text:'"My understanding is: the bank needs to decide how to respond to fintech-driven share loss — specifically whether to compete directly, partner, or acquire — in order to stabilize or regrow market share. Is that right?"', why:'Names the decision (how to respond), the options space implicitly (compete/partner/acquire), the goal (stabilize/regrow share), and checks it with the interviewer — all in one breath.'},
  explanation:'Say the objective back to the interviewer as a question, not a statement — "is that right?" invites a correction before you\'ve built 10 minutes of structure on a misunderstanding. This single habit prevents the single most costly failure mode in a case: solving the wrong problem well.',
  exercise:{type:'text', prompt:'"A pharma company\'s blockbuster drug loses patent protection in 3 years. The CEO wants our recommendation." Write a one-sentence, decision-oriented objective statement.',
    modelAnswer:'"The objective is to decide how the company should respond to the coming loss of patent exclusivity — for example through pipeline investment, M&A, or portfolio diversification — in order to protect revenue as generics enter the market. Is that the right framing?"'},
  commonMistakes:['Restating the topic instead of the decision.','Stating it so long it becomes a paragraph, not a sentence.','Never checking it with the interviewer, so a misunderstanding survives the whole case.'],
  reusableRule:'State the objective as a decision, in one sentence, and check it — "is that right?" — before structuring.',
  nextDrillId:null, relatedCaseIds:['profitability','market-entry'], relatedFrameworkIds:[],
},
{
  id:'case-management-basics', trackId:'fundamentals', title:'Case Management Basics', estimatedMinutes:6,
  primaryCompetency:'caseManagement', secondaryCompetencies:['communication'],
  prerequisites:['defining-objective'], concepts:['pacing','staying on objective'],
  thinkFirst:{prompt:'You\'re 20 minutes into a 35-minute case and realize your structure missed a major branch. What do you do in the next 10 seconds?'},
  coreIdea:'Case management is the meta-skill of steering the whole 30-45 minute conversation — pacing yourself, catching when you\'ve drifted from the objective, and recovering visibly rather than silently when something goes wrong. It\'s graded separately from any individual analytical step.',
  badExample:{text:'A candidate notices mid-case that a branch of their structure was wrong, but says nothing and just quietly keeps going as if it were fine.', why:'The interviewer sees the gap even if the candidate doesn\'t name it — staying silent about a known flaw reads as either not noticing or not being honest about it, both worse than naming it.'},
  strongExample:{text:'"Actually, stepping back — I think I under-weighted the customer side of this structure. Let me add a branch for customer retention before we go further."', why:'Naming the gap and visibly correcting course is exactly the behavior a real engagement needs — nobody expects a perfect first draft, they expect someone who catches and fixes their own errors.'},
  explanation:'Keep a mental (or written) checkpoint every 5-10 minutes: "does what I\'m doing right now still serve the objective?" If the answer is no, say so out loud and redirect — don\'t wait for the interviewer to catch it for you.',
  exercise:{type:'text', prompt:'You spend 6 minutes deep in a cost-driver rabbit hole and realize it\'s not moving you toward the objective. Write the exact sentence you\'d say to redirect.',
    modelAnswer:'"I want to pause here — I\'ve spent a few minutes on cost drivers but I don\'t think this is the highest-leverage branch given our objective. Can I shift to look at the revenue side instead?"'},
  commonMistakes:['Never checking back in against the objective once structuring is done.','Treating any deviation as a failure to hide, rather than a normal thing to name and fix.','Losing track of time and rushing the recommendation.'],
  reusableRule:'Every few minutes, silently ask "does this still serve the objective?" — and say so out loud the moment the answer is no.',
  nextDrillId:'client-question', relatedCaseIds:[], relatedFrameworkIds:[],
},
);
