// consultingContent/quant.js — Track: Quantitative Reasoning (7 modules)
// Numeric exercises use {type:'numeric', correctAnswer, toleranceAbs|tolerancePct} — graded
// deterministically by consultingEngine.js's checkQuantAnswer(), never by AI. Market Sizing and
// Sanity Checking are deliberately {type:'text'} instead — the skill being tested there is the
// decomposition/approach, not landing on one exact number, so forcing a numeric check would be
// dishonest precision. See consultingEngine.js for the checker itself.
CONSULTING_MODULES.push(
{
  id:'consulting-math-fundamentals', trackId:'quant', title:'Consulting Math Fundamentals', estimatedMinutes:7,
  primaryCompetency:'quantitativeReasoning', secondaryCompetencies:[],
  prerequisites:[], concepts:['mental math','rounding','anchor numbers'],
  thinkFirst:{prompt:'Revenue is $84M, costs are $61M. Roughly what\'s the profit margin — without a calculator, in under 10 seconds?'},
  coreIdea:'Case math rewards SPEED and DIRECTION more than decimal precision. Round to clean numbers, compute a defensible estimate fast, and only sharpen the precision if the case specifically calls for it. $84M ≈ $85M, $61M ≈ $60M — profit ≈ $25M, margin ≈ 25/85 ≈ 29%. Close enough, seconds not minutes.',
  badExample:{text:'Candidate reaches for exact long division on 84 and 61, taking 45 seconds of silent calculation before answering "27.38%."', why:'The extra precision (27.38% vs. ~29%) almost never changes the business conclusion, but the 45 seconds of silence reads as a candidate who can\'t estimate — a core consulting skill.'},
  strongExample:{text:'"Roughly — $84M minus $61M is about $23M profit, over $84M revenue, so call it around 27-28% margin." Stated within a few seconds, out loud, while working.', why:'Fast, verbalized, and directionally precise — exactly what a partner needs in a live meeting where nobody\'s handing you a calculator.'},
  explanation:'Build a small toolkit: round to the nearest clean number before dividing; know that dividing by numbers near 100 is nearly free (X/100 ≈ X%); keep a couple of fraction-to-percent anchors memorized (1/3≈33%, 1/7≈14%, 1/8≈12.5%).',
  exercise:{type:'numeric', prompt:'Revenue is $84M, costs are $61M. What is the profit margin, as a percentage (round to the nearest whole percent)?', correctAnswer:27, toleranceAbs:2, unit:'%',
    modelAnswer:'Profit = 84-61 = 23. Margin = 23/84 ≈ 27%.'},
  commonMistakes:['Chasing decimal precision the case doesn\'t need.','Doing math silently instead of narrating it, which makes the interviewer unable to follow (or catch) your reasoning.','Not rounding before dividing, making the arithmetic needlessly hard.'],
  reusableRule:'Round early, compute fast, narrate as you go — precision only when the case specifically demands it.',
  nextDrillId:'mental-math', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'percent-change', trackId:'quant', title:'Percent Change', estimatedMinutes:6,
  primaryCompetency:'quantitativeReasoning', secondaryCompetencies:[],
  prerequisites:['consulting-math-fundamentals'], concepts:['percent change','base effects'],
  thinkFirst:{prompt:'Revenue grew from $120M to $150M. What\'s the percent increase?'},
  coreIdea:'Percent change = (new − old) / old, always relative to the OLD/starting value — a mistake candidates make constantly is dividing by the new value instead, or by the difference of two percentages instead of the right base.',
  badExample:{text:'"Revenue went from $120M to $150M, so that\'s a $30M change over $150M, about 20%."', why:'Divided by the NEW value ($150M) instead of the old/starting value ($120M) — the correct base for a percent INCREASE is always where you started from.'},
  strongExample:{text:'"$30M increase over the original $120M base — that\'s 25%."', why:'Correctly anchors the percentage to the starting value, which is the only way "percent increase" is a well-defined, comparable number.'},
  explanation:'A related trap: if margin moves from 20% to 25%, that\'s a 5 PERCENTAGE POINT increase, not a "5% increase" — a 5% increase off a 20% base would only be 21%. Percentage points and percent change are different units; mixing them up is one of the most common case-math errors.',
  exercise:{type:'numeric', prompt:'A company\'s operating margin moved from 20% to 25%. Express this as a percent CHANGE in the margin (not percentage points) — i.e., (25-20)/20, as a percentage, rounded to the nearest whole number.', correctAnswer:25, toleranceAbs:2, unit:'%',
    modelAnswer:'(25-20)/20 = 5/20 = 25%. Note this is different from "5 percentage points" — both are correct descriptions, but they answer different questions.'},
  commonMistakes:['Dividing by the new value instead of the old/starting value.','Confusing percentage points with percent change.','Not stating which base the percentage is calculated against when reporting a number.'],
  reusableRule:'Percent change is always (new − old) / OLD — and percentage points are not the same unit as percent change.',
  nextDrillId:'mental-math', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'breakeven', trackId:'quant', title:'Breakeven', estimatedMinutes:7,
  primaryCompetency:'quantitativeReasoning', secondaryCompetencies:['businessJudgment'],
  prerequisites:['percent-change'], concepts:['breakeven volume','fixed vs variable cost'],
  thinkFirst:{prompt:'Fixed costs are $2M/year. Each unit sold contributes $40 toward covering those fixed costs. How many units need to sell to break even?'},
  coreIdea:'Breakeven volume = Fixed Costs / Contribution Margin per unit. It answers "how much do we need to sell before we stop losing money" — a question that comes up constantly in pricing, new-product, and capacity cases.',
  badExample:{text:'"$2M in fixed costs, divided by $40... let me think... that\'s a big number, maybe 500 units?"', why:'$2,000,000/40 = 50,000, not 500 — a basic division error, and the candidate didn\'t sanity-check that "500 units to cover $2M in fixed costs at $40 each" is obviously too small (500×40=$20,000, nowhere close to $2M).'},
  strongExample:{text:'"$2M divided by $40 per unit — that\'s 50,000 units to break even. Worth checking: 50,000 times $40 is $2M, so that checks out."', why:'Correct division, AND a quick sanity check multiplying back to confirm the answer — exactly the discipline that catches arithmetic slips before they compound into a wrong recommendation.'},
  explanation:'Always sanity-check a breakeven number against something you can picture — is 50,000 units a lot or a little for this business? If the company currently sells 200,000 units/year, breakeven at 50,000 is a comfortable cushion; if it sells 55,000, that\'s a much tighter, riskier situation worth flagging.',
  exercise:{type:'numeric', prompt:'Fixed costs are $2,000,000/year. Contribution margin per unit is $40. How many units must be sold to break even?', correctAnswer:50000, tolerancePct:2, unit:'units',
    modelAnswer:'2,000,000 / 40 = 50,000 units.'},
  commonMistakes:['Dividing the wrong way (contribution margin ÷ fixed costs) and getting a nonsense tiny number.','Forgetting to sanity-check the answer against the business\'s actual scale.','Using total cost per unit instead of contribution margin per unit in the denominator.'],
  reusableRule:'Breakeven units = Fixed Costs ÷ Contribution Margin per unit — then sanity-check the answer against real scale.',
  nextDrillId:'mental-math', relatedCaseIds:['profitability'], relatedFrameworkIds:[],
},
{
  id:'contribution-margin', trackId:'quant', title:'Contribution Margin', estimatedMinutes:6,
  primaryCompetency:'quantitativeReasoning', secondaryCompetencies:['businessJudgment'],
  prerequisites:['breakeven'], concepts:['contribution margin','variable cost'],
  thinkFirst:{prompt:'A product sells for $25. Variable cost per unit is $18. What\'s the contribution margin per unit, and as a percentage of price?'},
  coreIdea:'Contribution margin (price minus variable cost, per unit) tells you how much EACH ADDITIONAL unit sold contributes toward covering fixed costs and profit — it\'s the single most useful number for "should we sell more of this" or "should we take this incremental order" questions.',
  badExample:{text:'"Price is $25, so let\'s use the full cost — including a share of fixed costs, say $22 total — contribution margin is $3."', why:'Mixing in an allocated share of FIXED costs corrupts contribution margin — it should only ever subtract the VARIABLE cost, since fixed costs don\'t change with one more unit sold.'},
  strongExample:{text:'"Price $25 minus variable cost $18 — contribution margin is $7 per unit, or 28% of price."', why:'Correctly isolates variable cost only, giving a clean, directly usable number for volume-based decisions.'},
  explanation:'Contribution margin is why a company can rationally accept an order priced BELOW full cost (if it\'s still above variable cost) when it has spare capacity — every unit above variable cost still contributes something toward fixed costs, which are being paid regardless.',
  exercise:{type:'numeric', prompt:'Price is $25, variable cost per unit is $18. What is the contribution margin as a percentage of price (round to the nearest whole percent)?', correctAnswer:28, toleranceAbs:2, unit:'%',
    modelAnswer:'CM = 25-18 = $7. CM% = 7/25 = 28%.'},
  commonMistakes:['Including fixed costs in the calculation instead of only variable costs.','Confusing contribution margin (per unit or % of price) with gross margin or net margin, which are different things.','Not recognizing when contribution margin alone justifies accepting a below-full-cost order.'],
  reusableRule:'Contribution margin = Price − Variable Cost only — never subtract allocated fixed costs.',
  nextDrillId:'mental-math', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'weighted-average', trackId:'quant', title:'Weighted Average', estimatedMinutes:6,
  primaryCompetency:'quantitativeReasoning', secondaryCompetencies:[],
  prerequisites:['contribution-margin'], concepts:['weighted average','blended metrics'],
  thinkFirst:{prompt:'Segment A is 60% of revenue with a 20% margin. Segment B is 40% of revenue with a 5% margin. What\'s the company\'s blended (overall) margin?'},
  coreIdea:'A blended/overall metric across segments is a WEIGHTED average — weighted by each segment\'s share of the relevant base (usually revenue) — never a simple unweighted average of the segment numbers.',
  badExample:{text:'"20% and 5%, average that... 12.5%."', why:'A simple average ignores that the two segments are different sizes — it silently assumes they\'re 50/50, when Segment A is actually 60% of revenue and should count for more.'},
  strongExample:{text:'"Weight by revenue share: 60% times 20%, plus 40% times 5% — that\'s 12% plus 2%, so 14% blended margin."', why:'Correctly weights each segment\'s margin by its actual share of revenue, producing the true blended figure.'},
  explanation:'The general form: blended metric = Σ(weight_i × value_i), where weights sum to 100%. This shows up constantly — blended margins across product lines, blended growth rates across regions, blended prices across customer segments.',
  exercise:{type:'numeric', prompt:'Segment A: 60% of revenue, 20% margin. Segment B: 40% of revenue, 5% margin. What is the blended company margin, as a percentage?', correctAnswer:14, toleranceAbs:1, unit:'%',
    modelAnswer:'0.6×20 + 0.4×5 = 12 + 2 = 14%.'},
  commonMistakes:['Taking a simple unweighted average of the segment values.','Weighting by the wrong base (e.g., unit count instead of revenue, when revenue is what the question is about).','Forgetting the weights must sum to 100% (or 1.0).'],
  reusableRule:'Blended metric = weight × value, summed across segments — never a simple average unless the weights are actually equal.',
  nextDrillId:'mental-math', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'market-sizing', trackId:'quant', title:'Market Sizing', estimatedMinutes:9,
  primaryCompetency:'quantitativeReasoning', secondaryCompetencies:['businessJudgment','structuring'],
  prerequisites:['weighted-average'], concepts:['market sizing','top-down vs bottom-up'],
  thinkFirst:{prompt:'Estimate the annual market size (in $) for premium dog food in the US. Don\'t look anything up — sketch your approach in a sentence or two before you compute anything.'},
  coreIdea:'Market sizing is graded on the STRUCTURE of your decomposition and the reasonableness of your assumptions — not on landing within 5% of the "real" number, which doesn\'t exist as a single fact anyway. Pick a clean top-down (total population × penetration × spend) or bottom-up (unit economics × volume) path and state your assumptions explicitly as you go.',
  badExample:{text:'"US population is 330 million... premium dog food... let me think... I\'ll guess $50 billion."', why:'No visible decomposition — a number pulled from thin air, with no assumptions the interviewer could evaluate, agree with, or correct.'},
  strongExample:{text:'"I\'ll go top-down: ~330M people, ~40% own a dog (~130M dog owners, though many own multiple dogs — I\'ll approximate at the person level). Say a third of dog owners buy premium food, spending roughly $300/year more than standard food — that\'s about 43M premium buyers × maybe $500/year total premium spend ≈ $20B. I\'d sanity check this against total US pet food spend, which I\'d guess is somewhere around $50-60B, so premium at ~$20B being a third of that feels directionally plausible."', why:'Every assumption is stated explicitly and could be individually challenged or corrected — the interviewer can see exactly where to push back, and the final sanity check against a known anchor makes the number more credible.'},
  explanation:'State each assumption as you make it ("I\'ll assume X"), so the interviewer can redirect you if a specific assumption is wrong — that\'s far more valuable than silently computing and announcing only the final number. End with a sanity check against any anchor number you\'re more confident in.',
  exercise:{type:'text', prompt:'Estimate the annual market size for gym memberships in a mid-size US city of 1 million people. Show your decomposition and state each assumption explicitly.',
    modelAnswer:'Top-down: 1M people → maybe 15-20% are gym members (adjust for age distribution) ≈ 150,000-200,000 members. Average membership cost, blending budget and premium gyms, maybe $50/month ≈ $600/year. Market size ≈ 175,000 × $600 ≈ $105M/year. Explicitly flag the membership-rate and average-price assumptions as the two most uncertain, most-worth-challenging inputs.'},
  commonMistakes:['Announcing a final number with no visible decomposition.','Using suspiciously precise inputs (e.g., "37.2% of households") without justification.','Never sanity-checking the final number against any anchor or known reference point.'],
  reusableRule:'State every assumption out loud as you build the estimate, and sanity-check the final number against something you\'re more confident in.',
  nextDrillId:'estimation', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'sanity-checking', trackId:'quant', title:'Sanity Checking', estimatedMinutes:6,
  primaryCompetency:'quantitativeReasoning', secondaryCompetencies:['businessJudgment'],
  prerequisites:['market-sizing'], concepts:['sanity check','order of magnitude'],
  thinkFirst:{prompt:'A team calculates that a mid-size city\'s coffee shops generate $500M in combined annual revenue. The city has 500,000 people. Does this pass a basic sanity check?'},
  coreIdea:'A sanity check asks "does this number make sense given something I already know is roughly true" — it\'s the single fastest way to catch an arithmetic error or a bad assumption before it becomes a wrong recommendation delivered with false confidence.',
  badExample:{text:'"$500M in coffee shop revenue for the city — okay, moving on to the next part of the case."', why:'$500M / 500,000 people = $1,000 per person per year on coffee shops alone — an implausibly high number that a 5-second check would have caught, but the candidate moved on without checking.'},
  strongExample:{text:'"Wait — $500M over 500,000 people is $1,000 per person per year just on coffee shops. That seems too high; average coffee spend is probably closer to $200-300/year per person, so I\'d expect something more like $100-150M. Let me re-check my math."', why:'Caught the implausible number immediately by dividing back into a per-person figure and comparing it to a rough real-world anchor — exactly the habit that prevents a wrong number from surviving into a final recommendation.'},
  explanation:'Good anchors to divide back into: per person, per day, per store, per employee — whichever makes the number comparable to something you have real intuition for. If a number "feels" off, it usually is; trust that instinct enough to actually check it.',
  exercise:{type:'text', prompt:'A team estimates a national ride-sharing company completes 50 million rides per DAY in the US. Is this plausible? Show the check you\'d run.',
    modelAnswer:'US population ≈ 330M. 50M rides/day would mean roughly 1 in 6-7 Americans takes a ride-share trip every single day — implausibly high (real figures are far lower, more like a few million rides/day). The check: divide the claimed number by population to get a per-person daily rate, then ask if that rate is realistic.'},
  commonMistakes:['Never dividing a big number back into a per-unit figure to check plausibility.','Accepting a number because the arithmetic that produced it was correct, without checking if the ANSWER itself makes sense.','Not having any anchor numbers memorized to compare against.'],
  reusableRule:'Divide any big number into a per-person, per-day, or per-unit figure and ask: does that feel realistic?',
  nextDrillId:'estimation', relatedCaseIds:[], relatedFrameworkIds:[],
},
);
