// consultingContent/recommendation.js — Track: Recommendations (3 modules)
CONSULTING_MODULES.push(
{
  id:'final-recommendations', trackId:'recommendation', title:'Final Recommendations', estimatedMinutes:8,
  primaryCompetency:'recommendation', secondaryCompetencies:['communication','synthesis'],
  prerequisites:[], concepts:['answer first','executive communication'],
  thinkFirst:{prompt:'You\'ve diagnosed that a retailer\'s profit decline is driven by rising labor costs at underperforming stores. State your final recommendation in one opening sentence, the way you\'d say it to a CEO.'},
  coreIdea:'A strong final recommendation leads with the ANSWER, not the journey — a busy executive wants the recommendation first, then the 2-3 pieces of supporting evidence, then risks. Candidates who narrate their whole analytical journey before landing on a recommendation lose the audience.',
  badExample:{text:'"So we looked at revenue, that seemed stable, then we looked at costs, and we found labor costs were rising, especially at certain stores, so given all that, I\'d recommend addressing labor costs at underperforming stores."', why:'Buries the recommendation at the end of a chronological narrative — a busy executive has to wait through the whole analytical journey to hear the actual answer.'},
  strongExample:{text:'"My recommendation is to address rising labor costs at the underperforming store cohort specifically — that\'s the primary driver of the profit decline. This is based on two things: labor cost per store has risen fastest at exactly the stores where profit fell most, and revenue across the chain has stayed stable, ruling out a demand-side explanation."', why:'Leads with the recommendation in the first sentence, then supports it with exactly two pieces of evidence — structured for an audience with limited time and attention.'},
  explanation:'Structure: Recommendation (1 sentence) → Supporting evidence (2-3 bullets, not a full narrative) → Risks (1-2) → Next steps. This order works regardless of how you got there analytically — the delivery order is not the discovery order.',
  exercise:{type:'text', prompt:'You\'ve found that a SaaS company\'s churn is concentrated among customers on an old pricing plan, and the fix is to migrate them to a new plan. Write your opening recommendation sentence.',
    modelAnswer:'"My recommendation is to proactively migrate customers still on the legacy pricing plan to the current plan structure — churn is concentrated almost entirely in that legacy-plan cohort, and addressing it directly should meaningfully reduce overall churn."'},
  commonMistakes:['Narrating the analytical journey chronologically instead of leading with the answer.','Supporting the recommendation with too much evidence (more than 2-3 points) instead of the most important few.','Making a recommendation that doesn\'t clearly follow from the analysis presented.'],
  reusableRule:'Recommendation first, in one sentence — then 2-3 pieces of evidence, not the whole journey.',
  nextDrillId:'conclusion', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'risks-and-mitigations', trackId:'recommendation', title:'Risks and Mitigations', estimatedMinutes:7,
  primaryCompetency:'recommendation', secondaryCompetencies:['businessJudgment'],
  prerequisites:['final-recommendations'], concepts:['risk identification','mitigation'],
  thinkFirst:{prompt:'You recommend a company acquire a smaller competitor. What\'s the single most important risk you\'d flag, unprompted?'},
  coreIdea:'A recommendation without stated risks sounds naive, not confident — strong candidates proactively name the 1-2 biggest risks to their OWN recommendation and propose a mitigation, rather than waiting for the interviewer to poke holes in it.',
  badExample:{text:'"I recommend the acquisition." No mention of integration risk, cultural fit, or valuation risk unless directly asked.', why:'Sounds like the candidate hasn\'t stress-tested their own recommendation — real recommendations always carry risk, and not naming any makes the analysis look incomplete rather than confident.'},
  strongExample:{text:'"I recommend the acquisition, with one major risk to flag: integration risk, since the two companies run on different systems. I\'d mitigate this by running a phased integration with a dedicated transition team, rather than a single cutover."', why:'Names a specific, real risk unprompted and pairs it with a concrete mitigation — shows the recommendation was stress-tested, not just asserted.'},
  explanation:'Pick the risk that would most change your recommendation if it materialized — not a generic, low-stakes risk. A good risk-mitigation pair sounds like: "the biggest risk is X; I\'d mitigate it by Y" — specific on both sides.',
  exercise:{type:'text', prompt:'You recommend a hospital system reduce ER wait times by adding overnight staff. Name one risk and one mitigation.',
    modelAnswer:'Risk: added staffing cost could worsen the hospital\'s already-thin margins if wait-time improvement doesn\'t translate into measurable outcomes (patient volume, reduced readmissions). Mitigation: pilot the added staffing at one location first, with clear metrics, before committing to a system-wide rollout.'},
  commonMistakes:['Not naming any risk unless the interviewer asks.','Naming a generic, low-stakes risk instead of the one that would actually matter most.','Naming a risk with no proposed mitigation.'],
  reusableRule:'Name the ONE risk that would most undermine your recommendation, unprompted, with a specific mitigation.',
  nextDrillId:'conclusion', relatedCaseIds:['ma'], relatedFrameworkIds:[],
},
{
  id:'next-steps', trackId:'recommendation', title:'Next Steps', estimatedMinutes:6,
  primaryCompetency:'recommendation', secondaryCompetencies:['caseManagement'],
  prerequisites:['risks-and-mitigations'], concepts:['next steps','what would change the answer'],
  thinkFirst:{prompt:'You\'ve given your final recommendation and named a key risk. What\'s a strong closing next-steps statement?'},
  coreIdea:'Closing with concrete next steps — and naming what evidence would change your recommendation — signals that you understand this is a real decision under incomplete information, not a final, unquestionable verdict from a 30-minute conversation.',
  badExample:{text:'"So yeah, that\'s my recommendation." Then silence.', why:'Ends abruptly with no forward motion — doesn\'t show awareness that a real recommendation, made with limited data in 30 minutes, would need validation before being acted on.'},
  strongExample:{text:'"Before finalizing, I\'d want to validate the labor cost data at the store level with actual HR records, and pilot the fix at 2-3 stores before a full rollout. If the pilot showed the cost issue didn\'t actually resolve, that would make me reconsider whether store management practices, not headcount, is the real driver."', why:'Names concrete validation steps AND explicitly states what evidence would change the recommendation — shows appropriate humility about the limits of a case-interview-length analysis.'},
  explanation:'A strong close has two parts: (1) what would you actually DO next to validate or implement this (a pilot, more data, a specific test), and (2) what specific finding would make you change your mind. Both signal real, non-dogmatic thinking.',
  exercise:{type:'text', prompt:'You\'ve recommended a company enter a new geographic market. Write a closing next-steps statement covering both validation and what would change your mind.',
    modelAnswer:'"Next, I\'d want to run a small pilot or test launch in one city within the new market before a full rollout, and validate our assumptions about local demand with primary research. If the pilot showed significantly weaker demand than assumed, or if a strong local competitor emerged that we hadn\'t accounted for, I\'d reconsider the recommendation."'},
  commonMistakes:['Ending the case with no forward-looking statement at all.','Naming next steps that are vague ("do more research") rather than specific.','Never stating what would actually change the recommendation.'],
  reusableRule:'Close with a specific validation step AND a specific statement of what would change your mind.',
  nextDrillId:'conclusion', relatedCaseIds:[], relatedFrameworkIds:[],
},
);
