// consultingContent/structuring.js — Track: Structuring (6 modules)
CONSULTING_MODULES.push(
{
  id:'what-good-structure-means', trackId:'structuring', title:'What Good Structure Actually Means', estimatedMinutes:8,
  primaryCompetency:'structuring', secondaryCompetencies:['problemDefinition'],
  prerequisites:['defining-objective'], concepts:['structure vs framework','objective-driven branches'],
  thinkFirst:{prompt:'"A grocery chain\'s profit fell 20% this year." Before reading on, sketch (in words) 3 top-level branches you\'d use to structure this — don\'t just name a framework.'},
  coreIdea:'Good structure is a set of branches that (a) are directly testable against the objective, (b) don\'t overlap, and (c) together cover the real space of possible answers. A memorized framework recited without adapting it to the specific client is not structure — it\'s decoration.',
  badExample:{text:'"I\'ll use the profitability framework: Revenue = Price x Volume, Costs = Fixed + Variable." Then the candidate never connects any branch back to what specifically might be true for a grocery chain.', why:'This is a generic template, not a structure built for this client. It sounds organized but doesn\'t actually direct the investigation toward the likely cause.'},
  strongExample:{text:'"Given profit fell but I don\'t yet know if it\'s revenue or cost driven, I\'d look first at revenue — has same-store traffic or basket size changed — and separately at cost — has COGS or labor cost per store moved. I\'d prioritize revenue first since grocery margins are typically thin and small price/volume shifts move profit a lot."', why:'The structure is built FOR a grocery chain specifically (traffic, basket size, thin margins) and comes with a stated prioritization, not just a list.'},
  explanation:'A useful test: could you defend, out loud, why each branch belongs and why you ordered them the way you did? If you can\'t explain the "why" behind a branch, it\'s filler, not structure.',
  exercise:{type:'text', prompt:'"A B2B software company\'s customer churn doubled." Name 2 top-level branches (not a whole tree) and briefly justify why you\'d prioritize investigating one first.',
    modelAnswer:'Branches: (1) product/service issues (bugs, missing features, support quality) and (2) customer fit/value issues (wrong segment being sold to, ROI not being realized). Prioritize (2) first if churn doubled suddenly — a sudden shift often signals a change in who\'s being sold to or a change in perceived value, rather than a slow-building product problem.'},
  commonMistakes:['Reciting a memorized framework without adapting it to the client.','Listing branches with no stated prioritization.','Overlapping branches that double-count the same underlying driver.'],
  reusableRule:'Every branch must answer: why does this belong, and why is it here in the order I put it?',
  nextDrillId:'framework-gen', relatedCaseIds:['profitability'], relatedFrameworkIds:[],
},
{
  id:'mece-without-forcing', trackId:'structuring', title:'MECE Without Forcing It', estimatedMinutes:7,
  primaryCompetency:'structuring', secondaryCompetencies:[],
  prerequisites:['what-good-structure-means'], concepts:['MECE','mutually exclusive','collectively exhaustive'],
  thinkFirst:{prompt:'You structure a cost problem as "labor costs, non-labor costs, and overtime costs." What\'s wrong with this as a MECE set?'},
  coreIdea:'MECE (Mutually Exclusive, Collectively Exhaustive) is a QUALITY CHECK on a structure you already built for a reason — not a goal to force from scratch. Strong candidates build a structure around the objective first, then sanity-check it for overlap and gaps; weak candidates start from "how do I make this MECE" and end up with buckets that don\'t map to anything real.',
  badExample:{text:'"Labor costs, non-labor costs, and overtime costs" as three parallel buckets.', why:'Overtime costs are a SUBSET of labor costs, not a separate category — this double-counts, violating "mutually exclusive," because the same dollar can land in two buckets.'},
  strongExample:{text:'"Labor costs (including overtime) and non-labor costs" — two clean buckets — with a note: "within labor, I\'d also want to separately look at overtime specifically since it\'s often the fastest-moving piece."', why:'The top-level split is genuinely MECE; the interest in overtime is preserved as a SUB-branch, not a competing top-level bucket — no double-counting, no lost information.'},
  explanation:'A fast test: pick any single dollar of cost or unit of revenue — can you place it in exactly one of your buckets? If it could plausibly go in two, or in none, your structure isn\'t MECE yet. Fix it by adjusting bucket definitions, not by abandoning structure altogether.',
  exercise:{type:'text', prompt:'A candidate structures "customers" as "new customers, existing customers, and high-value customers." Identify the MECE problem and fix it in one sentence.',
    modelAnswer:'"High-value customers" overlaps with both "new" and "existing" — it\'s a different dimension (value) crossed with the first dimension (tenure), not a third parallel bucket. Fix: keep "new vs. existing" as the top split, and treat "value" as a second, separate dimension you could cut EITHER bucket by if useful.'},
  commonMistakes:['Creating a bucket that\'s actually a subset of another bucket.','Forcing MECE so hard the buckets become abstract and disconnected from the actual business.','Treating MECE as the goal instead of a check on a structure built for a reason.'],
  reusableRule:'Pick one dollar or one unit — can you place it in exactly one bucket? If not, fix the buckets before moving on.',
  nextDrillId:'framework-critique', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'issue-trees', trackId:'structuring', title:'Issue Trees', estimatedMinutes:8,
  primaryCompetency:'structuring', secondaryCompetencies:['prioritization'],
  prerequisites:['mece-without-forcing'], concepts:['issue tree','top-down decomposition'],
  thinkFirst:{prompt:'"Why did website conversion rate drop 30%?" Sketch the first two levels of an issue tree — the root question, then 2-3 branches, then one level deeper under just ONE of those branches.'},
  coreIdea:'An issue tree is a top-down decomposition where the root is the actual question, each branch is a possible driver or lever, and you go DEEPER only on the branches that matter most — not evenly across every branch. Depth without breadth-first prioritization wastes time on low-value branches.',
  badExample:{text:'A candidate draws a tree with 5 top-level branches and spends equal time expanding all 5 one level deeper, regardless of which seem likely.', why:'This treats depth as a checklist rather than a prioritized investigation — real time is finite, and spreading it evenly means shallow answers everywhere instead of a real answer somewhere.'},
  strongExample:{text:'"Of these three branches — traffic quality, page experience, checkout friction — checkout friction seems most likely given conversion dropped suddenly rather than gradually. Let me go deeper there first: was there a checkout flow change, a payment processor issue, or new required fields?"', why:'States which branch is most likely and WHY (suddenness of the drop), then goes deep there first — efficient use of limited time.'},
  explanation:'Build the tree breadth-first for the top level (name all the real branches), then go depth-first only on the highest-likelihood or highest-impact branch. State your prioritization logic out loud — it\'s as valuable to the interviewer as the tree itself.',
  exercise:{type:'text', prompt:'Root question: "Why did a mobile game\'s daily active users drop 25% in one month?" Name 3 top-level branches, then say which you\'d go deeper on first and why.',
    modelAnswer:'Branches: (1) acquisition — fewer new installs, (2) retention — existing users leaving faster, (3) technical — a bug or update breaking the experience. Given a sudden one-month drop rather than a gradual decline, I\'d go deeper on (3) technical first — sudden drops often trace to a specific release or outage rather than a slow erosion in acquisition or retention.'},
  commonMistakes:['Building a tree with no stated prioritization of which branch to explore first.','Going infinitely deep on the first branch without checking if it\'s actually the highest-value one.','Branches that aren\'t real decompositions of the root, just loosely related topics.'],
  reusableRule:'Build the top level broad, then go deep only on the branch you can justify as most likely or highest-impact — and say why.',
  nextDrillId:'framework-gen', relatedCaseIds:['profitability'], relatedFrameworkIds:[],
},
{
  id:'hypothesis-driven-structuring', trackId:'structuring', title:'Hypothesis-Driven Structuring', estimatedMinutes:8,
  primaryCompetency:'hypothesisDriven', secondaryCompetencies:['structuring'],
  prerequisites:['issue-trees'], concepts:['hypothesis-driven thinking','point of view from day one'],
  thinkFirst:{prompt:'"A regional bank\'s loan default rate doubled in one year." What\'s your single leading hypothesis for the cause — stated specifically, not vaguely?'},
  coreIdea:'Hypothesis-driven structuring means forming a specific, falsifiable best guess BEFORE gathering data, then building your structure to test that guess efficiently — not exploring with a blank, "open" mind. A vague hypothesis ("maybe it\'s a market issue") can\'t actually be tested; a specific one ("underwriting standards loosened for a specific loan segment") can.',
  badExample:{text:'"My hypothesis is that something changed in the lending business." Then the candidate explores broadly with no particular lens.', why:'This isn\'t a hypothesis — it\'s a restatement of the problem. It gives no direction for what data to look for first.'},
  strongExample:{text:'"My leading hypothesis is that underwriting standards loosened for one specific loan category — say, a new higher-risk product line launched around the same time defaults started rising. I\'d want to check default rates BY loan category and by vintage (when the loan was originated) to test this."', why:'Specific enough to be wrong, and it directly implies what data to request next — that\'s the entire point of a hypothesis.'},
  explanation:'A hypothesis is not a guess you\'re emotionally attached to — it\'s a tool for efficient investigation. When data contradicts it, that\'s a GOOD outcome (you\'ve learned something specific), not a failure. Update it immediately and say so out loud.',
  exercise:{type:'text', prompt:'"An airline\'s on-time performance dropped sharply at one hub airport, but not systemwide." State a specific, testable hypothesis and the first piece of data you\'d request to test it.',
    modelAnswer:'Hypothesis: something hub-specific changed — likely a staffing shortage, a gate/runway capacity constraint, or a new maintenance issue concentrated at that hub. First data request: on-time performance and staffing levels at that hub over the same period, to see if the timing lines up with a specific operational change.'},
  commonMistakes:['Stating a hypothesis too vague to be tested or falsified.','Refusing to update the hypothesis when data contradicts it.','Treating "I don\'t have a hypothesis yet" as acceptable rather than forcing a specific best guess.'],
  reusableRule:'State a hypothesis specific enough that it could be proven wrong — and update it the moment data says it is.',
  nextDrillId:'hyp-gen', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'tailoring-structures', trackId:'structuring', title:'Tailoring Structures', estimatedMinutes:7,
  primaryCompetency:'structuring', secondaryCompetencies:['businessJudgment'],
  prerequisites:['hypothesis-driven-structuring'], concepts:['tailoring','avoiding memorized frameworks'],
  thinkFirst:{prompt:'A memorized "profitability framework" says look at Price, Volume, Fixed Costs, Variable Costs. For a subscription SaaS business specifically, what would you ADD or CHANGE about that generic structure?'},
  coreIdea:'Every generic framework is a starting scaffold, not a finished structure — the skill is adapting it to the SPECIFIC business model, industry, and objective in front of you. Interviewers can immediately tell when a structure was memorized versus built for the client at hand.',
  badExample:{text:'A candidate applies the same "Revenue/Cost" profitability tree to a subscription software company as they would to a manufacturer — no mention of churn, retention, or recurring revenue dynamics.', why:'Subscription businesses live and die on retention and expansion revenue, not one-time volume — a generic tree misses the single most important lever for this business model.'},
  strongExample:{text:'"For a subscription business, I\'d adapt the revenue side specifically: new customer acquisition, expansion revenue from existing customers, and churn/contraction — since recurring revenue dynamics matter more here than a one-time price times volume calculation would."', why:'Explicitly names what\'s different about THIS business model and adjusts the branches accordingly, rather than forcing a generic template onto it.'},
  explanation:'Before applying any framework, ask: "what\'s structurally different about this business/industry that a generic template would miss?" Common differentiators: recurring vs. one-time revenue, asset-heavy vs. asset-light, regulated vs. unregulated, two-sided market vs. one-sided.',
  exercise:{type:'text', prompt:'You\'re given a generic "market entry" framework (market attractiveness, competitive position, entry mode, financials). How would you tailor it specifically for a case about entering a heavily regulated industry like healthcare or banking?',
    modelAnswer:'Add regulatory approval timeline and cost as an explicit branch under entry mode/financials — in a regulated industry, the path to market (licensing, compliance, approval time) can be the binding constraint on the whole decision, not just a footnote, and generic market-entry frameworks don\'t surface it by default.'},
  commonMistakes:['Applying the same structure regardless of business model or industry.','Not naming out loud what\'s different about this specific client.','Tailoring so much the structure loses any recognizable logic.'],
  reusableRule:'Before applying any framework, name out loud what\'s structurally different about this client that a generic version would miss.',
  nextDrillId:'framework-critique', relatedCaseIds:['market-entry'], relatedFrameworkIds:[],
},
{
  id:'prioritization-structuring', trackId:'structuring', title:'Prioritization', estimatedMinutes:7,
  primaryCompetency:'prioritization', secondaryCompetencies:['structuring'],
  prerequisites:['tailoring-structures'], concepts:['prioritization','ranking branches'],
  thinkFirst:{prompt:'You have 4 plausible branches to investigate and 15 minutes left. How do you decide which ONE to go deepest on?'},
  coreIdea:'Generating a MECE set of buckets is necessary but not sufficient — the differentiating skill is prioritizing WHICH branch to actually investigate first, under real time pressure, and being able to defend that choice. Many candidates can list branches; fewer can rank them convincingly.',
  badExample:{text:'"I have four branches, let me start with the first one" — investigated in the order they were listed, with no stated logic.', why:'Order-of-listing is not a prioritization logic — it signals the candidate hasn\'t actually thought about which branch matters most, just which came to mind first.'},
  strongExample:{text:'"Of these four, I\'d prioritize customer churn first — it\'s both the most likely driver given the timing, and the easiest to get data on quickly. I\'ll hold the pricing and competitive branches unless churn doesn\'t explain enough of the gap."', why:'States two independent reasons (likelihood AND ease of getting evidence) and commits to a specific order with a stated fallback — a real prioritization, not a guess.'},
  explanation:'Two honest criteria for prioritization: (1) how LIKELY is this branch to be the real driver, given what you already know, and (2) how QUICKLY can you get evidence to confirm or rule it out. Rank by a combination of both, not just intuition.',
  exercise:{type:'text', prompt:'Four possible causes of a manufacturer\'s rising defect rate: (1) new supplier, (2) equipment aging, (3) staff turnover, (4) process change. Rank your top 2 to investigate first and justify briefly.',
    modelAnswer:'Top 2: (1) new supplier and (4) process change — both are discrete, recent, identifiable EVENTS that are easy to check against the timing of when defects started rising. Equipment aging and staff turnover are more gradual and harder to pin to a specific inflection point, so they\'re lower priority to check first.'},
  commonMistakes:['Investigating branches in the order they were listed rather than by actual priority.','Prioritizing based on personal interest rather than likelihood/evidence-speed.','Never revisiting the priority order as new evidence comes in.'],
  reusableRule:'Rank branches by likelihood AND speed-to-evidence — and say the ranking out loud before you start.',
  nextDrillId:'issue-rank', relatedCaseIds:[], relatedFrameworkIds:[],
},
);
