// consultingContent/synthesis.js — Track: Synthesis (4 modules)
CONSULTING_MODULES.push(
{
  id:'what-synthesis-is', trackId:'synthesis', title:'What Synthesis Actually Is', estimatedMinutes:7,
  primaryCompetency:'synthesis', secondaryCompetencies:['communication'],
  prerequisites:[], concepts:['synthesis vs summary'],
  thinkFirst:{prompt:'You just learned revenue fell 12%, entirely driven by lower volume while price stayed constant. What would you say before moving on?'},
  coreIdea:'Synthesis is not repeating the numbers you just learned — it is answering three questions in sequence: what did we learn, why does it matter, and what should we investigate next. A summary restates facts; a synthesis converts facts into direction.',
  badExample:{text:'"Revenue declined by 12%, volume went down, and price stayed the same."', why:'Accurate but purely descriptive — it restates the data without saying what it MEANS or where to go next. This is a summary, not a synthesis.'},
  strongExample:{text:'"The decline appears to be a volume problem rather than a pricing problem, so I\'d next determine whether volume loss is concentrated by customer, product, or geography."', why:'Names the implication (volume problem, not pricing) and immediately converts it into a specific next step — exactly the two things a summary is missing.'},
  explanation:'Every synthesis should be able to answer, out loud, in sequence: "What did we learn? Why does it matter for our objective? What should we look at next?" If you\'ve only answered the first question, you\'ve summarized, not synthesized.',
  exercise:{type:'text', prompt:'You just learned: customer complaints doubled in the last quarter, concentrated almost entirely in one product line. Write a synthesis (not a summary).',
    modelAnswer:'"This looks like a product-specific issue rather than a company-wide service problem, since complaints are concentrated in one line — I\'d want to check what changed for that specific product recently, like a formula change, a new supplier, or a recent update."'},
  commonMistakes:['Restating the numbers without stating what they mean.','Stopping after "why it matters" without naming a next step.','Synthesizing facts that aren\'t actually connected to the case objective.'],
  reusableRule:'Synthesis = what we learned + why it matters + what to investigate next — all three, every time.',
  nextDrillId:'conclusion', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'interim-synthesis', trackId:'synthesis', title:'Interim Synthesis', estimatedMinutes:7,
  primaryCompetency:'synthesis', secondaryCompetencies:['communication','caseManagement'],
  prerequisites:['what-synthesis-is'], concepts:['interim synthesis','checkpoint synthesis'],
  thinkFirst:{prompt:'You\'re 15 minutes into a case, having just finished exploring the cost side of a profitability problem. Before moving to the revenue side, what would you say to the interviewer?'},
  coreIdea:'An interim synthesis is a checkpoint you give partway through a case — not just at the end — that recaps what\'s been established so far and states where you\'re headed next. It keeps the interviewer (and you) oriented, and signals that you\'re managing the case actively rather than drifting from branch to branch.',
  badExample:{text:'Candidate finishes the cost analysis and immediately starts asking for revenue data with no transition.', why:'The interviewer has no idea whether the candidate concluded anything from the cost analysis, or is just moving on because they ran out of things to ask — it looks aimless even if the thinking underneath was sound.'},
  strongExample:{text:'"So on the cost side, I found costs have stayed roughly proportional to volume — nothing unusual there. That points me toward the revenue side being the more likely driver of the profit decline. I\'d like to look at revenue by segment next."', why:'Recaps the conclusion from the branch just finished, states the implication, and previews the next branch — exactly what keeps a 40-minute case feeling directed rather than exploratory.'},
  explanation:'Use an interim synthesis every time you finish a major branch of your structure — not just at the very end of the case. It costs 10-15 seconds and buys you credit for staying organized across the whole conversation.',
  exercise:{type:'text', prompt:'You\'ve just finished analyzing customer acquisition data and found nothing unusual — acquisition has been steady. Write the interim synthesis you\'d give before moving to the next branch.',
    modelAnswer:'"Customer acquisition has been steady, so that\'s likely not the driver of the issue we\'re seeing — this points me toward looking at the retention or existing-customer side instead, which I\'d like to explore next."'},
  commonMistakes:['Moving between branches with no transition or recap.','Giving an interim synthesis only at the very end of the case, not along the way.','Summarizing data without stating the implication for where to go next.'],
  reusableRule:'Every time you finish a branch, give a 10-second interim synthesis before moving to the next one.',
  nextDrillId:'conclusion', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'post-math-synthesis', trackId:'synthesis', title:'Post-Math Synthesis', estimatedMinutes:6,
  primaryCompetency:'synthesis', secondaryCompetencies:['quantitativeReasoning'],
  prerequisites:['interim-synthesis'], concepts:['so what after calculation'],
  thinkFirst:{prompt:'You just calculated that breakeven volume is 50,000 units, and the company currently sells 55,000. What do you say immediately after finishing the math?'},
  coreIdea:'Finishing a calculation is not the end of the task — the number needs to be converted into a business statement immediately, in the same breath, not left for the interviewer to interpret. "So what" always follows "what\'s the number."',
  badExample:{text:'"Breakeven is 50,000 units." Then silence, waiting for the interviewer to ask what that means.', why:'Delivers a correct number with zero interpretation — leaves the most valuable part of the exercise (what it means for the business) undone.'},
  strongExample:{text:'"Breakeven is 50,000 units, and they\'re currently selling 55,000 — so they\'re only about 10% above breakeven, which is a thin cushion. A relatively small volume drop could push them into losses, so I\'d want to understand how stable that volume actually is."', why:'Immediately converts the raw number into a business risk statement and a natural next question — no gap for the interviewer to fill in.'},
  explanation:'Build the habit of never letting a calculated number be the last thing you say — always follow it with "which means..." Even a single sentence of interpretation turns arithmetic into insight.',
  exercise:{type:'text', prompt:'You just calculated that a proposed price increase would raise margin from 20% to 24%, but historical data shows a similar past increase caused an 8% volume drop. What do you say immediately after the calculation?',
    modelAnswer:'"Margin improves from 20% to 24% on paper, but if we see a similar 8% volume drop as last time, the net profit impact could be much smaller than it looks — I\'d want to model the combined effect of higher margin and lower volume together before recommending this."'},
  commonMistakes:['Stating a calculated number with no interpretation.','Interpreting the number in a way disconnected from the case objective.','Treating the calculation itself as the deliverable rather than a means to an insight.'],
  reusableRule:'Never let a calculated number be the last word — always follow it with "which means..."',
  nextDrillId:'conclusion', relatedCaseIds:[], relatedFrameworkIds:[],
},
{
  id:'exhibit-synthesis', trackId:'synthesis', title:'Exhibit Synthesis', estimatedMinutes:6,
  primaryCompetency:'synthesis', secondaryCompetencies:['exhibitInterpretation'],
  prerequisites:['post-math-synthesis'], concepts:['exhibit synthesis','case pivot synthesis'],
  thinkFirst:{prompt:'You\'ve just been shown an exhibit that contradicts your leading hypothesis. What\'s the first thing you should say?'},
  coreIdea:'When an exhibit changes your understanding of the case — confirms, contradicts, or complicates your hypothesis — that shift itself deserves an explicit synthesis, not a silent internal update. Naming the pivot out loud is what separates a candidate who\'s truly reasoning in real time from one who\'s just reacting to data.',
  badExample:{text:'An exhibit contradicts the candidate\'s hypothesis, and the candidate quietly pivots to a new line of questioning without acknowledging the contradiction.', why:'The interviewer can\'t tell whether the candidate noticed the contradiction or just got lost — silently changing direction reads as confusion, even when the underlying reasoning was sound.'},
  strongExample:{text:'"That\'s interesting — this actually contradicts my original hypothesis that it was a pricing issue, since price clearly didn\'t move. Let me update: I now think this points more toward a volume-side explanation, and I\'d like to look at customer segments next."', why:'Explicitly names the contradiction, updates the hypothesis on the spot, and states the new direction — visible, honest, real-time reasoning.'},
  explanation:'Treat every new exhibit as a checkpoint: does this CONFIRM, CONTRADICT, or COMPLICATE what I believed before? Say which one it is, out loud, before moving on — this is one of the clearest signals of genuine hypothesis-driven thinking an interviewer can observe.',
  exercise:{type:'text', prompt:'Your hypothesis was that a decline in sales was due to weak marketing. A new exhibit shows marketing spend and quality were unchanged, but a competitor launched a cheaper alternative the same month. Write the synthesis you\'d give.',
    modelAnswer:'"This contradicts my marketing hypothesis — spend and quality held steady, so that\'s probably not the driver. Given the timing lines up with a competitor\'s cheaper launch, I now think competitive pricing pressure is the more likely explanation, and I\'d want to check whether our customer losses concentrate among price-sensitive segments."'},
  commonMistakes:['Silently changing direction without naming why.','Not distinguishing whether new data confirms, contradicts, or complicates the prior view.','Ignoring an exhibit that contradicts the current hypothesis instead of engaging with it.'],
  reusableRule:'Every new exhibit: name whether it confirms, contradicts, or complicates your hypothesis — out loud — before moving on.',
  nextDrillId:'conclusion', relatedCaseIds:[], relatedFrameworkIds:[],
},
);
